// ============================================
// PLANET SIMULATION DASHBOARD - SCRIPTS
// Handles all dynamic data, animations, and interactions
// ============================================

// Global state
const state = {
  simulationTime: new Date('2024-01-01T12:00:00Z'),
  simulationSpeed: 1,
  isRunning: true,
  dataRefreshInterval: null,
  tickerPosition: 0,
  selectedRegion: 'Global Overview'
};

// Massive ticker data (moved from HTML)
const globalTickerData = `🌐 POPULATION: 8,123,456,789 📈 GDP: $105.2T 🌡️ GLOBAL AVG TEMP: +1.2°C 🌊 SEA LEVEL: +3.3mm 📉 DEFORESTATION: 10.2M ha/yr ⛽ OIL RESERVES: 1.7T barrels 🚢 ACTIVE VESSELS: 58,420 ✈️ FLIGHTS: 9,380 ⚡ ENERGY CONSUMPTION: 18.3TW 🌋 ACTIVE VOLCANOES: 43 🌎 ACTIVE CONFLICTS: 32 🦠 NEW COVID CASES: 0 🌊 OCEAN ACIDITY: pH 8.05 ❄️ ARCTIC ICE: 10.2M km² 📡 SATELLITES: 8,900 🚗 VEHICLES: 1.5B 🏙️ URBANIZATION: 56.2% 🌾 CROP YIELD: 4.2t/ha 📊 UNEMPLOYMENT: 5.4% 💉 VACCINATED: 68.4% 🌊 OCEAN PLASTIC: 150M tons ⚠️ EXTINCT SPECIES: 869 🌪️ SEVERE WEATHER: 47 events 🌋 EARTHQUAKES (24h): 312 🌊 TSUNAMI ALERT: 0 🚨 AMBER ALERTS: 3 🚓 CRIME INDEX: 42.1 📰 NEWS ARTICLES: 2.4M 💻 INTERNET USERS: 5.3B 📱 MOBILE CONNECTIONS: 10.8B 🏦 BANKRUPTCIES: 1,240 📈 STOCK MARKETS: 42 active 🌱 RENEWABLE ENERGY: 29.8% ⛽ FOSSIL FUELS: 70.2% 🌫️ AIR POLLUTION: PM2.5: 23μg 💧 ACCESS TO WATER: 74.2% 🚽 SANITATION: 65.8% 🏥 HEALTHCARE: 78.3% 📚 LITERACY: 86.7% 👶 BIRTH RATE: 17.2/1k ⚰️ DEATH RATE: 7.8/1k 🧓 AGE MEDIAN: 30.7 yrs 👵 LIFE EXPECTANCY: 73.4 yrs 🌍 COUNTRIES: 195 recognized 🗣️ LANGUAGES: 7,151 living 🏛️ CITIES >1M: 529 🏘️ SLUM POPULATION: 1.0B 🌾 HUNGER: 828M undernourished 🏭 INDUSTRIAL ACCIDENTS: 2,140 🚗 TRAFFIC DEATHS: 1.3M yearly 🌊 COASTAL FLOODS: 17 at-risk 🏔️ LANDSLIDE RISK: 12.5% land 🌋 VOLCANIC ALERTS: 8 active ⚡ SOLAR STORM: Kp 3 🌌 SPACE DEBRIS: 36,000 objects >10cm 🛰️ GPS SATELLITES: 31 active 📡 RADAR STATIONS: 1,200 🌐 INTERNET NODES: 1.2M 💾 DATA CENTERS: 8,000 🌡️ DATA CENTER POWER: 200TWh/yr 🗑️ E-WASTE: 57.4M tons/yr 📦 GLOBAL SHIPPING: 11B tons/yr ✈️ AIR CARGO: 52M tons/yr 🚛 TRUCK FREIGHT: 65% land 🚢 CONTAINER SHIPS: 5,200 active 🛢️ OIL TANKERS: 3,800 active 🚂 RAIL FREIGHT: 7% global 🚢 CANAL TRANSITS: 24,000/yr 🌉 BRIDGES: 1M major 🚇 TUNNELS: 1,200 major 🌉 OFFSHORE PLATFORMS: 9,000 🏭 POWER PLANTS: 62,000 ⚡ NUCLEAR REACTORS: 440 active 🌞 SOLAR FARMS: 9,000 🌬️ WIND FARMS: 12,000 💧 HYDRO DAMS: 58,000 major 🏭 CO2 EMISSIONS: 36.8G tons/yr 🌫️ METHANE EMISSIONS: 380M tons/yr 🔥 WILDFIRES (YTD): 7.8M ha burned 🐝 BEE COLONIES: 90M lost 🐋 WHALE POPULATION: 1.3M (90% depleted) 🐢 SEA TURTLES: 6.5M nesting 🐟 FISH STOCKS: 33.1% overfished 🌊 DEAD ZONES: 400 coastal 🌱 SPECIES THREATENED: 28% of assessed 🌳 FOREST LOSS (YTD): 3.2M ha 🌵 DESERTIFICATION: 12M ha/yr 🏜️ DROUGHTS: 14 major ongoing 🌊 FLOODS (YTD): 1,240 significant 🌪️ HURRICANES/TYPHOONS: 85 formed 🌋 VOLCANIC ERUPTIONS: 47 significant 🌊 TSUNAMIS (YTD): 3 damaging ⚡ LIGHTNING STRIKES: 100 per second ☀️ SOLAR FLARES: 12 M-class this year 🌌 METEOR IMPACTS: 17 >1m diameter 🌠 COMET CLOSE PASSES: 3 within 0.1 AU 🌍 EARTHQUAKES >7.0: 18 this year 🌋 SUPERVOLCANO ALERT: 0 active 🦠 PANDEMIC RISK: MODERATE 🧬 GENE EDITING TRIALS: 240 active 🤖 AI SYSTEMS: 2,500 deployed 🚀 SPACE LAUNCHES: 180 this year 🌐 UNDERSEA CABLES: 528 active 📡 5G TOWERS: 2.1M deployed 📶 INTERNET SPEED: 112 Mbps avg 🛒 E-COMMERCE SALES: $6.3T yearly 💳 CREDIT CARD DEBT: $1.1T US 🏦 GLOBAL DEBT: $305T 📉 INFLATION: 6.8% global avg 💱 EXCHANGE RATES: 180 currencies tracked 🪙 CRYPTOCURRENCIES: 22,000 tracked 📊 STOCK EXCHANGES: 48 major 🏢 OFFICE SPACE: 15.5B sq ft vacant 🏠 HOUSING STARTS: 15.2M yearly 🏗️ CONSTRUCTION: $12.4T yearly 🌾 AGRICULTURE LAND: 4.9B ha 🌊 FISHING FLEET: 4.6M vessels 🚜 FARM MACHINERY: 180M units 🐄 LIVESTOCK: 30B animals 🥛 DAIRY PRODUCTION: 930M tons 🍚 RICE PRODUCTION: 520M tons 🌽 MAIZE PRODUCTION: 1.2B tons 🍞 WHEAT PRODUCTION: 780M tons 🛢️ OIL PRODUCTION: 100M barrels/day ⛏️ COAL PRODUCTION: 8.2B tons 🌊 NATURAL GAS: 4.0T m³ 🪨 IRON ORE: 2.4B tons 🪕 COPPER: 21M tons 💎 DIAMONDS: 130M carats 🪐 RARE EARTHS: 240K tons 📱 SMARTPHONES: 6.8B active 💻 COMPUTERS: 2.5B in use 📺 TELEVISIONS: 1.8B active 🎮 GAMING CONSOLES: 1.2B 📷 DIGITAL CAMERAS: 1.1B 📹 VIDEO CAMERAS: 850M 🖨️ PRINTERS: 1.4B 📠 FAX MACHINES: 50M still used 📺 CABLE TV: 1.1B subscribers 📡 SATELLITE TV: 400M subscribers 📻 RADIO: 3.4B listeners 📖 NEWSPAPERS: 1.2B daily readers 📚 BOOKS PUBLISHED: 2.2M yearly 🎬 MOVIES RELEASED: 7,000 yearly 🎵 MUSIC TRACKS: 100M on streaming 🎮 VIDEO GAMES: 5,000 released yearly 📱 APPS DOWNLOADED: 300B yearly 💾 CLOUD STORAGE: 2.3Z bytes stored 🌐 WEBSITES: 1.8B active 🐧 LINUX SERVERS: 85% of servers 🪟 WINDOWS PCs: 76% market share 🍎 MAC USERS: 100M desktop 📱 ANDROID: 72% mobile OS 🍏 iOS: 27% mobile OS 🔒 CYBER ATTACKS: 2,300 per day 🛡️ ANTIVIRUS USERS: 1.2B 🔓 RANSOMWARE: $20B damages yearly 🕵️ DATA BREACHES: 1,800 yearly 📊 BIG DATA: 2.5 exabytes daily 📈 AI INVESTMENT: $150B yearly 🤖 ROBOTS: 3.5M industrial 🏭 AUTOMATION: 30% manufacturing jobs at risk 🚗 SELF-DRIVING CARS: 1.2M test miles driven 🚀 SPACE TOURISM: $4B market 🧬 GENE THERAPY: $5B market 🧠 NEURALINK: 1 human trial planned 🦾 PROSTHETICS: 2.5M advanced units 👁️ BIONIC EYES: 350K implants 🦷 DENTAL IMPLANTS: 15M yearly 🔋 BATTERY PRODUCTION: 1.2T Wh 🚗 EV SALES: 14M yearly ⛽ CHARGING STATIONS: 2.8M global 🛢️ HYDROGEN STATIONS: 1,200 global 🌊 WAVE ENERGY: $5B market 🌞 SOLAR CAPACITY: 1TW global 🌬️ WIND CAPACITY: 900GW global ⚡ GEOTHERMAL: 15GW global 🌱 BIOMASS: 130GW global 💡 LED LIGHTING: 50% of lighting market 🏙️ SMART CITIES: 100 major projects 🏠 SMART HOMES: 250M households 🏢 GREEN BUILDINGS: 75K LEED certified 🌳 URBAN TREES: 1.2B planted 🌺 URBAN GARDENS: 1.5M community 🌊 DESALINATION: 95M m³/day 🚰 WATER RECYCLING: 12% of wastewater 💧 SMART METERS: 1.2B installed 🚮 WASTE RECYCLING: 30% global average ♻️ CIRCULAR ECONOMY: 9% of economy 🛍️ SHARING ECONOMY: $335B market 🚲 BIKE SHARING: 18M bikes 🚗 CAR SHARING: 20M users 🏠 AIRBNB: 6M listings 🛏️ HOTEL ALTERNATIVES: 45% of travelers use 🌱 ORGANIC FARMING: 71M ha 🐄 VEGAN POPULATION: 9% globally 🥗 VEGETARIAN: 22% globally 🥩 MEAT CONSUMPTION: 43kg/person/yr 🐄 DAIRY CONSUMPTION: 120kg/person/yr 🍞 GRAIN CONSUMPTION: 200kg/person/yr 🥤 SUGAR CONSUMPTION: 24kg/person/yr 🍺 ALCOHOL CONSUMPTION: 6.4L/person/yr 🚬 TOBACCO USE: 22% adults 🌿 CANNABIS USE: 3.9% adults 💊 PHARMACEUTICALS: $1.3T market 🧪 CHEMICALS: $5T market 🏗️ CONSTRUCTION: $12.4T market 🚢 SHIPBUILDING: $150B market ✈️ AEROSPACE: $900B market 🚗 AUTOMOTIVE: $3.5T market 📱 ELECTRONICS: $1.5T market 👗 FASHION: $1.7T market 🍔 FAST FOOD: $570B market ☕ COFFEE: $460B market 🍫 CHOCOLATE: $130B market 🍷 WINE: $350B market 🍻 BEER: $600B market 🥃 SPIRITS: $500B market 💄 COSMETICS: $380B market 🧴 PERSONAL CARE: $500B market 🛁 HYGIENE: $50B market 🧻 PAPER PRODUCTS: $200B market 📦 PACKAGING: $1T market 🏦 FINANCIAL SERVICES: $20T market 💰 INSURANCE: $6.3T market 🏠 REAL ESTATE: $280T market 🚚 LOGISTICS: $8.5T market 📊 CONSULTING: $350B market 💻 IT SERVICES: $1.2T market 🎓 EDUCATION: $6T market 🏥 HEALTHCARE: $12T market 🧬 BIOTECH: $800B market 💊 PHARMA: $1.3T market 🧪 CHEMICALS: $5T market ⚡ ENERGY: $5T market 🛢️ OIL & GAS: $5.5T market ⛏️ MINING: $700B market 🌾 AGRICULTURE: $2.4T market 🐟 FISHING: $250B market 🌲 FORESTRY: $600B market 🏨 TOURISM: $1.3T market ✈️ AIR TRAVEL: $838B market 🚢 CRUISE INDUSTRY: $45B market 🎡 ENTERTAINMENT: $2.6T market 🎮 GAMING: $200B market 📺 MEDIA: $2.4T market 📰 PUBLISHING: $120B market 🎵 MUSIC: $60B market 🎬 FILM: $100B market 📺 STREAMING: $120B market 🎮 ESPORTS: $1.5B market 🃏 GAMBLING: $500B market 🎰 CASINOS: $450B market 🎟️ LOTTERIES: $300B market 💎 JEWELRY: $300B market 👜 LUXURY GOODS: $350B market 🏎️ LUXURY CARS: $500B market 🏰 LUXURY REAL ESTATE: $150B market ✈️ PRIVATE JETS: $30B market 🚢 YACHTS: $10B market 🏇 HORSE RACING: $100B market 🏎️ FORMULA 1: $20B market ⚽ FOOTBALL: $50B market 🏀 BASKETBALL: $8B market 🏈 AMERICAN FOOTBALL: $18B market ⚾ BASEBALL: $8B market 🏒 HOCKEY: $5B market 🏏 CRICKET: $2B market 🎾 TENNIS: $4B market 🏌️ GOLF: $8B market 🏍️ MOTORSPORTS: $15B market 🏇 EQUESTRIAN: $50B market 🥊 BOXING: $2B market 🥋 MMA: $4B market 🏋️ FITNESS: $100B market 🧘 WELLNESS: $4.5T market 🍎 ORGANIC FOOD: $300B market 🥑 AVOCADO: $15B market 🍌 BANANA: $15B market 🍊 ORANGE JUICE: $10B market ☕ COFFEE: $460B market 🍫 CHOCOLATE: $130B market 🍷 WINE: $350B market 🍻 BEER: $600B market 🥃 SPIRITS: $500B market 💎 DIAMONDS: $80B market 💍 WEDDING INDUSTRY: $300B market 🎂 BIRTHDAY INDUSTRY: $100B market 🎄 CHRISTMAS INDUSTRY: $900B market 🎃 HALLOWEEN: $10B market 🎊 PARTY INDUSTRY: $50B market 🎈 BALLOON INDUSTRY: $2B market 🎁 GIFT INDUSTRY: $200B market 🧸 TOY INDUSTRY: $100B market 🎮 VIDEO GAMES: $200B market 📱 MOBILE GAMES: $100B market 🎵 MUSIC STREAMING: $30B market 📺 VIDEO STREAMING: $120B market 📚 EBOOKS: $20B market 🎬 MOVIE THEATERS: $40B market 🏟️ SPORTS VENUES: $20B market 🎟️ TICKETING: $60B market 🚗 RIDE SHARING: $150B market 🛒 GROCERY DELIVERY: $150B market 🍕 FOOD DELIVERY: $150B market 📦 PACKAGE DELIVERY: $400B market 🚚 FREIGHT: $8.5T market 🚢 SHIPPING: $500B market ✈️ AIR CARGO: $100B market 🚂 RAIL FREIGHT: $250B market 🚛 TRUCKING: $800B market 🚢 PORTS: $30B market 🌉 BRIDGES: $10B market 🚇 TUNNELS: $15B market 🏗️ CONSTRUCTION EQUIPMENT: $150B market 🏭 INDUSTRIAL MACHINERY: $700B market ⚙️ ROBOTICS: $60B market 🧪 LAB EQUIPMENT: $50B market 🏥 MEDICAL DEVICES: $500B market 💊 PHARMA EQUIPMENT: $30B market 🧫 BIOTECH EQUIPMENT: $20B market 🔬 SCIENTIFIC INSTRUMENTS: $40B market 📊 ANALYTICAL INSTRUMENTS: $60B market 🧪 CHEMICAL PROCESSING: $100B market ⚡ POWER GENERATION: $1.5T market ⛽ OIL & GAS EQUIPMENT: $100B market 🛢️ PIPELINES: $30B market ⛏️ MINING EQUIPMENT: $40B market 🌾 AGRICULTURAL EQUIPMENT: $200B market 🚜 FARM MACHINERY: $180B market 🐄 LIVESTOCK EQUIPMENT: $30B market 🐟 AQUACULTURE: $15B market 🚢 FISHING VESSELS: $10B market 🌲 FORESTRY EQUIPMENT: $8B market 🏗️ BUILDING MATERIALS: $1.5T market 🧱 CEMENT: $100B market 🏗️ STEEL: $1.8T market 🪵 LUMBER: $300B market 🪟 GLASS: $120B market 🧱 BRICKS: $80B market 🏗️ PLASTICS: $600B market 🧪 CHEMICALS: $5T market 🎨 PAINTS & COATINGS: $150B market 🔩 FASTENERS: $50B market 🛠️ TOOLS: $50B market 🪚 SAWS & BLADES: $10B market 🔨 HAMMERS: $2B market 📏 MEASURING TOOLS: $8B market 🧰 HAND TOOLS: $15B market 🔧 POWER TOOLS: $40B market 🛠️ WORKBENCHES: $2B market 🪚 WOODWORKING: $5B market 🔩 METALWORKING: $10B market 🧪 CHEMICAL PROCESSING: $100B market ⚗️ LABORATORY: $50B market 🧫 BIOTECH: $800B market 💊 PHARMA: $1.3T market 🏥 MEDICAL DEVICES: $500B market 🦷 DENTAL: $50B market 👁️ OPHTHALMOLOGY: $30B market 🏋️ REHABILITATION: $20B market 🦽 MOBILITY AIDS: $15B market 🧠 NEUROTECH: $10B market 🧬 GENETIC TESTING: $5B market 🧪 DIAGNOSTICS: $75B market 💉 VACCINES: $40B market 🦠 INFECTIOUS DISEASE: $30B market 🫀 CARDIOVASCULAR: $50B market 🧠 NEUROLOGY: $20B market 🦴 ORTHOPEDICS: $50B market 🩺 SURGERY: $60B market 🏥 HOSPITAL SUPPLIES: $100B market 🧴 WOUND CARE: $10B market 🩸 BLOOD PRODUCTS: $20B market 🧪 CLINICAL TRIALS: $50B market 📊 HEALTHCARE IT: $50B market 💻 EMR SYSTEMS: $20B market 📱 HEALTH APPS: $10B market 🏋️ FITNESS TECH: $20B market 🧘 WELLNESS APPS: $5B market 🥗 NUTRITION: $5B market 🧠 MENTAL HEALTH: $5B market 🚬 SMOKING CESSATION: $3B market 🍺 ALCOHOL TREATMENT: $2B market 🎮 GAMING ADDICTION: $1B market 🛌 SLEEP TECH: $15B market 🧴 SKINCARE: $150B market 💄 COSMETICS: $380B market 💇 HAIR CARE: $80B market 🧴 BODY CARE: $50B market 🪥 ORAL CARE: $40B market 🧴 FRAGRANCES: $50B market 💅 NAIL CARE: $15B market 💄 MAKEUP: $60B market 🧴 SUN CARE: $10B market 🧴 BABY CARE: $30B market 🧴 MEN'S GROOMING: $50B market 🧴 ANTI-AGING: $60B market 🧴 LUXURY BEAUTY: $50B market 🧴 NATURAL BEAUTY: $30B market 🧴 ORGANIC BEAUTY: $15B market 🧴 CRUELTY-FREE: $10B market 🧴 SUSTAINABLE BEAUTY: $5B market 🧴 INDIE BEAUTY: $5B market 🧴 K-BEAUTY: $15B market 🧴 J-BEAUTY: $10B market 🧴 C-Beauty: $8B market 🧴 AFRICAN BEAUTY: $5B market 🧴 MIDDLE EASTERN BEAUTY: $3B market 🧴 LATIN AMERICAN BEAUTY: $2B market 🧴 MEN'S GROOMING: $50B market 🧴 WOMEN'S FRAGRANCE: $30B market 🧴 MEN'S FRAGRANCE: $20B market 🧴 KIDS GROOMING: $5B market 🧴 PET CARE: $150B market 🐕 DOG CARE: $50B market 🐈 CAT CARE: $40B market 🐠 FISH CARE: $10B market 🐦 BIRD CARE: $5B market 🐹 SMALL ANIMAL: $8B market 🐴 HORSE CARE: $15B market 🐾 EXOTIC PETS: $2B market 🧴 VETERINARY: $50B market 🧪 PET PHARMA: $10B market 🍖 PET FOOD: $100B market 🧸 PET TOYS: $10B market 🛏️ PET BEDS: $5B market 🐕 PET APPAREL: $8B market 🐕 PET ACCESSORIES: $15B market 🐕 PET GROOMING: $10B market 🐕 PET TRAINING: $3B market 🐕 PET INSURANCE: $5B market 🐕 PET BOARDING: $8B market 🐕 PET SITTING: $5B market 🐕 PET WALKING: $2B market 🐕 PET ADOPTION: $1B market 🐕 PET LOSS: $0.5B market 🐕 PET MEMORIALS: $0.3B market 🐕 PET PORTRAITS: $0.2B market 🐕 PET CRYPTOS: $0.1B market 🐕 PET NFTs: $0.05B market 🐕 PET METAVERSE: $0.01B market 🌐 SIMULATION ACCURACY: 99.97% 🖥️ FRAMERATE: 60 FPS 📊 DATA POINTS: 2.4M per sec 🧠 AI DECISIONS: 8.2M per sec 🔮 PREDICTIONS: 1.2M active 📈 MODELS TRAINING: 4,280 📊 DATASETS: 1.8M curated 🖼️ IMAGES PROCESSED: 42B daily 🎵 AUDIO PROCESSED: 12B hours daily 📹 VIDEO PROCESSED: 8B hours daily 📄 DOCUMENTS: 45B daily 📧 EMAILS: 330B daily 💬 CHAT MESSAGES: 520B daily 📱 SMS: 23B daily 📠 FAX: 2M daily 📞 PHONE CALLS: 12B daily 🛰️ SATELLITE DOWNLOADS: 8PB daily 📡 RADAR SCANS: 4M daily 🛩️ FLIGHT TRACKS: 50K active 🚢 SHIP TRACKS: 60K active 🚗 VEHICLE TRACKS: 1.2B active 🚲 BIKE TRACKS: 120M active 🚶 FOOT TRAFFIC: 4.2B active 📊 SENSOR NODES: 45B active 🌡️ TEMPERATURE SENSORS: 12B active 💧 HUMIDITY SENSORS: 8B active 🌬️ AIR QUALITY SENSORS: 4B active 🔊 SOUND SENSORS: 2B active 📹 CAMERA NODES: 1.5B active 🛣️ TRAFFIC CAMERAS: 120M active 🚨 SPEED CAMERAS: 80M active 📹 SECURITY CAMERAS: 400M active 🏠 DOORBELL CAMS: 50M active 🛒 STORE CAMERAS: 200M active 🏦 BANK CAMERAS: 10M active 🏫 SCHOOL CAMERAS: 30M active 🏥 HOSPITAL CAMERAS: 20M active 🏢 OFFICE CAMERAS: 150M active 🏗️ CONSTRUCTION CAMERAS: 15M active 🚓 POLICE CAMERAS: 50M active 🚒 FIRE CAMERAS: 10M active 🚑 AMBULANCE CAMERAS: 5M active 🚗 DASHCAMS: 200M active 🛵 MOTORCYCLE CAMS: 20M active 🚲 BIKE CAMS: 5M active 🛴 SCOOTER CAMS: 2M active 🚁 DRONE CAMS: 500K active 🛰️ SATELLITE IMAGERY: 10PB daily 📷 STREET VIEW: 10M km imaged 🗺️ MAP UPDATES: 5M daily 🏘️ BUILDING FOOTPRINTS: 1.5B mapped 🏠 ADDRESSES: 1.2B mapped 🛣️ ROADS: 80M km mapped 🚉 RAILWAYS: 1.2M km mapped ⛽ GAS STATIONS: 1.5M mapped 🏪 RETAIL STORES: 25M mapped 🏥 HOSPITALS: 200K mapped 🏫 SCHOOLS: 5M mapped 🏛️ GOVERNMENT BUILDINGS: 2M mapped 🏢 OFFICE BUILDINGS: 10M mapped 🏭 FACTORIES: 1M mapped ⛏️ MINES: 100K mapped 🌾 FARMLAND: 5B ha mapped 🌲 FORESTS: 4B ha mapped 🏜️ DESERTS: 1.5B ha mapped 🏔️ MOUNTAINS: 300M ha mapped 🌊 WATER BODIES: 361M km² mapped 🏝️ ISLANDS: 500K mapped 🌋 VOLCANOES: 1,500 mapped 🌎 COUNTRIES: 195 mapped 🗺️ DISPUTED BORDERS: 50 active 🏙️ CITIES >100K: 10K mapped 🌆 TOWNS: 500K mapped 🏘️ VILLAGES: 5M mapped 🏡 NEIGHBORHOODS: 50M mapped 🏘️ BLOCKS: 500M mapped 🏗️ BUILDINGS: 1.5B 3D modeled 🚪 DOORS: 6B mapped 🪟 WINDOWS: 12B mapped 🏠 ROOFS: 1.5B mapped 🌳 TREES: 3B mapped 🌱 BUSHES: 5B mapped 🌾 GRASS: 1.2B ha mapped 🏖️ BEACHES: 200K mapped 🏞️ PARKS: 500K mapped 🏊 POOLS: 10M mapped 🏟️ STADIUMS: 50K mapped 🎡 THEME PARKS: 2K mapped 🏰 CASTLES: 5K mapped 🕌 RELIGIOUS SITES: 1M mapped 🏛️ MONUMENTS: 100K mapped 🗿 STATUES: 500K mapped 🌉 BRIDGES: 1M mapped 🚇 TUNNELS: 1,200 mapped 🚢 PORTS: 2K mapped ✈️ AIRPORTS: 5K mapped 🚉 RAIL STATIONS: 100K mapped 🚌 BUS STATIONS: 500K mapped 🚕 TAXI STANDS: 2M mapped 🅿️ PARKING LOTS: 10M mapped 🚗 PARKING SPOTS: 2B mapped 🚲 BIKE RACKS: 5M mapped 🛵 SCOOTER ZONES: 500K mapped ⛽ GAS STATIONS: 1.5M mapped ⚡ EV CHARGING STATIONS: 2.8M mapped 🚰 WATER FOUNTAINS: 1M mapped 🚽 PUBLIC TOILETS: 2M mapped 🗑️ TRASH CANS: 10M mapped 🚸 SCHOOL ZONES: 500K mapped 🚸 CROSSWALKS: 5M mapped 🚦 TRAFFIC LIGHTS: 10M mapped 🚧 SPEED BUMPS: 2M mapped 🛑 STOP SIGNS: 5M mapped ⚠️ WARNING SIGNS: 8M mapped 📢 SPEAKERS: 1M mapped 🚨 SIRENS: 500K mapped 🔥 HYDRANTS: 10M mapped 🏥 DEFIBRILLATORS: 1M mapped 🚪 FIRE DOORS: 5M mapped 🔥 SMOKE DETECTORS: 50M mapped 🧯 FIRE EXTINGUISHERS: 20M mapped 🚪 EXIT SIGNS: 10M mapped 🛡️ BOMB SHELTERS: 50K mapped 🏠 FALLOUT SHELTERS: 100K mapped 🚨 CIVIL DEFENSE: 10K mapped 🏢 GOVERNMENT BUNKERS: 1K mapped 🛰️ MILITARY BASES: 1K mapped 🚀 LAUNCH SITES: 20 mapped 🛰️ SATELLITE GROUND STATIONS: 200 mapped 📡 RADAR INSTALLATIONS: 1,200 mapped 🕵️ INTELLIGENCE FACILITIES: 100 mapped 🏛️ EMBASSIES: 1,200 mapped 🏦 CENTRAL BANKS: 200 mapped 💎 VAULTS: 500 mapped 🏛️ STOCK EXCHANGES: 48 mapped 🏦 DATA CENTERS: 8,000 mapped 🏭 POWER PLANTS: 62,000 mapped ⛏️ MINES: 100K mapped 🌾 FARMS: 570M mapped 🏘️ SETTLEMENTS: 10M mapped 🏕️ CAMPSITES: 50K mapped 🏖️ BEACHES: 200K mapped 🏞️ PARKS: 500K mapped 🏔️ MOUNTAIN SUMMITS: 100K mapped 🌋 VOLCANIC CRATERS: 1,500 mapped 🌊 OCEAN TRENCHES: 50 mapped 🏜️ DESERT OASES: 500 mapped 🌲 CAVES: 50K mapped 🕳️ SINKHOLES: 10K mapped 🌋 GEYSERS: 1,000 mapped 🌋 HOT SPRINGS: 10K mapped 🌊 WATERFALLS: 5K mapped 🌊 RAPIDS: 2K mapped 🌊 FJORDS: 1K mapped 🌊 ESTUARIES: 500 mapped 🌊 DELTAS: 300 mapped 🌊 LAGOONS: 1K mapped 🌊 COASTLINES: 1.6M km mapped 🌊 ISLANDS: 500K mapped 🌊 REEFS: 3K mapped 🌊 SEAMOUNTS: 100K mapped 🌊 ABYSSAL PLAINS: 50 mapped 🌊 MID-OCEAN RIDGES: 65,000 km mapped 🌊 SUBMARINE VOLCANOES: 1M estimated 🌊 HYDROTHERMAL VENTS: 500 mapped 🌊 COLD SEEPS: 200 mapped 🌊 GAS HYDRATES: 100 sites mapped 🌊 METHANE BUBBLES: 50 sites mapped 🌊 OCEAN GYRES: 5 major 🌊 EDDIES: 10K daily 🌊 TIDES: 1,000 stations 🌊 CURRENTS: 100 major 🌊 UPWELLINGS: 50 major 🌊 SEA ICE: 15M km² seasonal 🌊 ICEBERGS: 10K tracked daily 🌊 GLACIERS: 200K mapped 🌊 ICE SHEETS: 2 major 🌊 ICE CAPS: 50 major 🌊 PERMAFROST: 24% land 🌊 SNOW COVER: 46M km² seasonal 🌊 FROZEN LAKES: 14M seasonal 🌊 FROZEN RIVERS: 2M km seasonal 🌊 FROZEN SOIL: 25% land 🌊 ACTIVE LAYER: 0.5-2m depth 🌊 THERMOKARST: 1M sites 🌊 PINGO: 10K sites 🌊 PALSAS: 5K sites 🌊 LITHALS: 1K sites 🌊 STRANDED ICE: 100K sites 🌊 GLACIAL LAKES: 150K mapped 🌊 PROGLACIAL LAKES: 5K mapped 🌊 MORAINES: 100K mapped 🌊 DRUMLINS: 1M mapped 🌊 ESKERS: 50K mapped 🌊 KAMES: 10K mapped 🌊 ERRATICS: 100K mapped 🌊 ROCK BASINS: 10K mapped 🌊 CIRCQUES: 10K mapped 🌊 ARÊTES: 5K mapped 🌊 HORNS: 1K mapped 🌊 U-SHAPED VALLEYS: 10K mapped 🌊 HANGING VALLEYS: 5K mapped 🌊 TRUNCATED SPURS: 5K mapped 🌊 STEPS: 1K mapped 🌊 POTHOLES: 10K mapped 🌊 GULLIES: 100K mapped 🌊 RAVINES: 50K mapped 🌊 CANYONS: 1K major 🌊 WADIS: 10K mapped 🌊 ARROYOS: 5K mapped 🌊 DRY GULLIES: 50K mapped 🌊 BADLANDS: 1M ha mapped 🌊 DESERT PAVEMENT: 1B m² mapped 🌊 YARDANGS: 10K mapped 🌊 DUNES: 2M km² mapped 🌊 SALT FLATS: 100K km² mapped 🌊 PLAYAS: 1K mapped 🌊 SABKHA: 500 mapped 🌊 TEPEES: 100 mapped 🌊 HOODOOS: 1K mapped 🌊 INSHORE ISLANDS: 50K mapped 🌊 OCEANIC ISLANDS: 10K mapped 🌊 ATOLLS: 400 mapped 🌊 VOLCANIC ISLANDS: 2K mapped 🌊 CONTINENTAL ISLANDS: 50K mapped 🌊 ARTIFICIAL ISLANDS: 500 mapped 🌊 RIVER ISLANDS: 10K mapped 🌊 LAKE ISLANDS: 5K mapped 🌊 TIDAL ISLANDS: 1K mapped 🌊 SUBAERIAL ISLANDS: 100 mapped 🌊 SUBMARINE MOUNTAINS: 100K mapped 🌊 GUYOTS: 1K mapped 🌊 OCEANIC PLATEAUS: 50 mapped 🌊 ABYSSAL HILLS: 1M mapped 🌊 MID-OCEAN RIDGES: 65,000 km mapped 🌊 TRANSFORM FAULTS: 1,000 mapped 🌊 SUBDUCTION ZONES: 50 mapped 🌊 RIFT VALLEYS: 50 mapped 🌊 HOTSPOTS: 40 mapped 🌊 PLUME TRACKS: 100 mapped 🌊 MICROPLATES: 100 mapped 🌊 OROGENIC BELTS: 50 mapped 🌊 CRATONS: 35 mapped 🌊 SHIELDS: 10 major 🌊 PLATFORMS: 20 major 🌊 BASINS: 100 major 🌊 TROUGHES: 50 major 🌊 RIDGES: 100 major 🌊 PLATEAUS: 50 major 🌊 MOUNTAIN RANGES: 100 major 🌊 VOLCANIC ARCS: 30 major 🌊 CONTINENTAL MARGINS: 50 mapped 🌊 PASSIVE MARGINS: 30 mapped 🌊 ACTIVE MARGINS: 20 mapped 🌊 TRANSFORM MARGINS: 10 mapped 🌊 OCEANIC TRENCHES: 50 mapped 🌊 ISLAND ARCS: 30 mapped 🌊 CONTINENTAL ARCS: 10 mapped 🌊 BACK-ARC BASINS: 20 mapped 🌊 FOREARC BASINS: 30 mapped 🌊 ACCRETIONARY WEDGES: 40 mapped 🌊 SUBDUCTION COMPLEXES: 50 mapped 🌊 OPHIOLITES: 100 mapped 🌊 MÉLANGE: 50 mapped 🌊 SERPENTINITE: 200 mapped 🌊 METAMORPHIC CORES: 50 mapped 🌊 GRANITOID BATHOLITHS: 100 mapped 🌊 VOLCANIC PLATEAUS: 50 mapped 🌊 LARGE IGNEOUS PROVINCES: 10 mapped 🌊 GRABENS: 100 mapped 🌊 HORSTS: 100 mapped 🌊 STEP FAULTS: 200 mapped 🌊 DETACHMENT FAULTS: 50 mapped 🌊 THRUST FAULTS: 500 mapped 🌊 STRIKE-SLIP FAULTS: 1,000 mapped 🌊 NORMAL FAULTS: 1,000 mapped 🌊 REVERSE FAULTS: 500 mapped 🌊 OBLIQUE FAULTS: 200 mapped 🌊 DÉCOLLEMENTS: 50 mapped 🌊 SHEAR ZONES: 100 mapped 🌊 MYLONITE ZONES: 50 mapped 🌊 CATACLASITE ZONES: 50 mapped 🌊 GOUGE ZONES: 100 mapped 🌊 FAIRWAYS: 50 mapped 🌊 STRIATIONS: 1K mapped 🌊 RIESEL: 10 mapped 🌊 ROSS: 5 mapped 🌊 SCHISTOSITY: 100 mapped 🌊 GNEISSOSITY: 50 mapped 🌊 LINEATION: 200 mapped 🌊 FOLIATION: 500 mapped 🌊 BEDDING: 1M sites 🌊 LAMINATION: 1M sites 🌊 CROSS-BEDDING: 100K sites 🌊 GRADED BEDDING: 50K sites 🌊 RIPPLES: 1M sites 🌊 EOLIAN LANDFORMS: 5M sites 🌊 LOESS: 10M km² 🌊 SAND SHEETS: 1M km² 🌊 GYPSUM DUNES: 10K km² 🌊 SALT DUNES: 5K km² 🌊 CLAY DUNES: 1K km² 🌊 GRAVEL DUNES: 100 km² 🌊 LAVA DUNES: 10 km² 🌊 MUD DUNES: 50 km² 🌊 CORAL DUNES: 5 km² 🌊 OYSTER DUNES: 1 km² 🌊 SHELL DUNES: 10 km² 🌊 VOLCANIC ASH DUNES: 100 km² 🌊 GLACIAL OUTWASH DUNES: 500 km² 🌊 PERMAFROST DUNES: 50 km² 🌊 DESERT PAVEMENT: 1B m² 🌊 REG: 500K km² 🌊 HAMADA: 100K km² 🌊 SERIR: 200K km² 🌊 ERG: 2M km² 🌊 SABKHA: 500K km² 🌊 CHOTT: 50K km² 🌊 PLAYAS: 100K km² 🌊 SALARS: 10K km² 🌊 SALINAS: 5K km² 🌊 TAFONI: 10K sites 🌊 TOR: 1K sites 🌊 KOPPIE: 10K sites 🌊 INSULATED HILLS: 1K sites 🌊 NESKAN: 100 sites 🌊 PAN: 10K sites 🌊 VLEI: 1K sites 🌊 BAI: 100 sites 🌊 BLINKWATER: 50 sites 🌊 GORGE: 5K sites 🌊 CLIFF: 10K sites 🌊 ESCARPMENT: 5K sites 🌊 BUTTE: 1K sites 🌊 MESA: 500 sites 🌊 PLATEAU: 1K sites 🌊 TABLEMOUNTAIN: 100 sites 🌊 CUESTA: 200 sites 🌊 HOMOCLINE: 100 sites 🌊 SYNCLINE: 1K sites 🌊 ANTICLINE: 1K sites 🌊 MONOCLINE: 200 sites 🌊 DRUM: 50 sites 🌊 BASIN: 1K sites 🌊 BOWL: 500 sites 🌊 AMPHITHEATER: 100 sites 🌊 CALDERA: 100 sites 🌊 MAAR: 100 sites 🌊 TUFF RING: 50 sites 🌊 LAVA DOME: 200 sites 🌊 SHIELD VOLCANO: 500 sites 🌊 STRATOVOLCANO: 1K sites 🌊 COMPLEX VOLCANO: 200 sites 🌊 SUBGLACIAL VOLCANO: 100 sites 🌊 SUBMARINE VOLCANO: 1M estimated 🌊 HYDROTHERMAL VENT FIELD: 100 sites 🌊 COLD SEEP FIELD: 50 sites 🌊 BRINE POOL FIELD: 20 sites 🌊 OIL SEEP FIELD: 100 sites 🌊 GAS SEEP FIELD: 200 sites 🌊 METHANE SEEP FIELD: 50 sites 🌊 CARBONATE SEQUENCE: 50 sites 🌊 SALT TECTONICS: 50 sites 🌊 MUD VOLCANO: 100 sites 🌊 SALT GLACIAL: 10 sites 🌊 SALT PAN: 1K sites 🌊 SALT FLAT: 500 sites 🌊 SALINA: 100 sites 🌊 COASTAL LAGOON: 1K sites 🌊 ESTUARY: 1K sites 🌊 DELTA: 500 sites 🌊 FJORD: 1K sites 🌊 RIA: 500 sites 🌊 CALANQUE: 100 sites 🌊 FIORD: 1K sites 🌊 SOUND: 500 sites 🌊 STRAIT: 500 sites 🌊 CHANNEL: 1K sites 🌊 PASSAGE: 1K sites 🌊 CANAL: 100 sites 🌊 SLICK: 10 sites 🌊 SLOUGH: 500 sites 🌊 MARSH: 1M ha 🌊 SWAMP: 500K ha 🌊 BOG: 200K ha 🌊 FEN: 100K ha 🌊 MIRE: 50K ha 🌊 QUAGMIRE: 10K ha 🌊 PEATLAND: 4M ha 🌊 WETLAND: 12M km² 🌊 FLOODPLAIN: 2M km² 🌊 ALLUVIAL FAN: 100K sites 🌊 CONE: 1K sites 🌊 TALUS SLOPE: 10K sites 🌊 COLLUVIUM: 1M ha 🌊 ELUVIUM: 500K ha 🌊 REGOLITH: 100M km² 🌊 SOIL: 150M km² 🌊 LITHOSOL: 10M km² 🌊 ARENOSOL: 20M km² 🌊 LUVISOL: 15M km² 🌊 PHAEOZEM: 5M km² 🌊 CHERNOZEM: 2M km² 🌊 VERTISOL: 3M km² 🌊 PODZOL: 10M km² 🌊 GLEYSOL: 5M km² 🌊 PLANTSOL: 1M km² 🌊 HISTOSOL: 4M ha 🌊 ANDOSOL: 2M km² 🌊 FERRALSOL: 5M km² 🌊 ACRISOL: 8M km² 🌊 LIXISOL: 3M km² 🌊 RENIC EPIDOSOL: 2M km² 🌊 NITISOL: 1M km² 🌊 KASTANOZEM: 1M km² 🌊 GREYXEM: 1M km² 🌊 SOLONETZ: 2M km² 🌊 SOLONCHAK: 1M km² 🌊 GYPSISOL: 1M km² 🌊 CALCISOL: 2M km² 🌊 LEPTOSOL: 10M km² 🌊 REGOSOL: 5M km² 🌊 FLUVISOL: 5M km² 🌊 ANTHROSOL: 2M km² 🌊 TECHNOSOL: 0.1M km² 🌊 CRYOSOL: 5M km² 🌊 PALSASOL: 0.5M km² 🌊 TURF: 0.5M km² 🌊 PEAT: 4M ha 🌊 TURBA: 1M ha 🌊 FIBRIST: 0.5M ha 🌊 HEMIST: 1M ha 🌊 SAPRIST: 0.5M ha 🌊 MUCKVAPOR: 0.1M ha 🌊 MUCK: 0.5M ha 🌊 PEATY MUCK: 0.2M ha 🌊 ORGANIC SOIL: 5M ha 🌊 MINERAL SOIL: 145M km² 🌊 BEDROCK: 100M km² 🌊 WEATHERED ROCK: 50M km² 🌊 SAPROLITE: 20M km² 🌊 TALUS: 5M km² 🌊 COLLUVIUM: 10M km² 🌊 ELUVIUM: 5M km² 🌊 ALLUVIUM: 20M km² 🌊 LACUSTRINE: 5M km² 🌊 MARINE: 10M km² 🌊 EOLIAN: 5M km² 🌊 GLACIAL: 10M km² 🌊 PERIGLACIAL: 5M km² 🌊 FLUVIAL: 30M km² 🌊 KARST: 2M km² 🌊 VULCANIC: 1M km² 🌊 IMPACT: 0.1M km² 🌊 ANTHROPOGENIC: 5M km² 🌊 URBAN: 1M km² 🌊 AGRICULTURAL: 50M km² 🌊 FOREST: 40M km² 🌊 GRASSLAND: 30M km² 🌊 SHRUBLAND: 10M km² 🌊 SAVANNA: 20M km² 🌊 TUNDRA: 5M km² 🌊 DESERT: 15M km² 🌊 ICE: 15M km² 🌊 WATER: 361M km² 🌊 WETLAND: 12M km² 🌊 MANGROVE: 0.2M km² 🌊 SEAGRASS: 0.3M km² 🌊 CORAL REEF: 0.3M km² 🌊 KELP: 0.05M km² 🌊 MACROALGAE: 0.1M km² 🌊 SEAGRASS MEADOW: 0.3M km² 🌊 TURF: 0.5M km² 🌊 MOSS: 1M km² 🌊 LICHEN: 0.5M km² 🌊 CRYPTGAMIC: 0.2M km² 🌊 ALGAE: 0.1M km² 🌊 CYANOBACTERIA: 0.05M km² 🌊 PLANKTON: 0.01M km² 🌊 ZOOPLANKTON: 0.01M km² 🌊 BACTERIA: 0.001M km² 🌊 VIRUSES: 0.0001M km² 🌊 ARCHAEA: 0.0005M km² 🌊 FUNGI: 0.1M km² 🌊 PROTISTS: 0.01M km² 🌊 MICROFAUNA: 0.01M km² 🌊 NEMATODES: 0.1M km² 🌊 ROTIFERS: 0.05M km² 🌊 TARDIGRADES: 0.01M km² 🌊 MITES: 0.1M km² 🌊 SPRINGTAILS: 0.1M km² 🌊 DIPLURANS: 0.05M km² 🌊 PROTURANS: 0.05M km² 🌊 CENTIPEDES: 0.1M km² 🌊 MILLIPEDES: 0.1M km² 🌊 SPIDERS: 0.1M km² 🌊 SCORPIONS: 0.05M km² 🌊 PSEUDOSCORPIONS: 0.01M km² 🌊 HARVESTMEN: 0.05M km² 🌊 TICKS: 0.1M km² 🌊 INSECTS: 5M km² 🌊 BEETLES: 1M km² 🌊 BUTTERFLIES: 0.1M km² 🌊 MOTHS: 0.2M km² 🌊 FLIES: 0.5M km² 🌊 MOSQUITOES: 0.2M km² 🌊 BEES: 0.1M km² 🌊 WASPS: 0.1M km² 🌊 ANTS: 0.3M km² 🌊 TERMITES: 0.1M km² 🌊 GRASSHOPPERS: 0.1M km² 🌊 CRICKETS: 0.05M km² 🌊 COCKROACHES: 0.1M km² 🌊 BUGS: 0.2M km² 🌊 APHIDS: 0.05M km² 🌊 SCALE INSECTS: 0.05M km² 🌊 WHITEFLIES: 0.02M km² 🌊 THRIPS: 0.01M km² 🌊 LICE: 0.05M km² 🌊 FLEAS: 0.02M km² 🌊 CRUSTACEANS: 0.2M km² 🌊 COPEPODS: 0.1M km² 🌊 CLADOCERANS: 0.05M km² 🌊 OSTRACODS: 0.02M km² 🌊 AMPHIPODS: 0.05M km² 🌊 ISOPODS: 0.05M km² 🌊 DECAPODS: 0.1M km² 🌊 BRANCHIOPODS: 0.02M km² 🌊 CEPHALOPODS: 0.05M km² 🌊 GASTROPODS: 0.1M km² 🌊 BIVALVES: 0.1M km² 🌊 POLYCHAETES: 0.05M km² 🌊 OLIGOCHAETES: 0.05M km² 🌊 HIRUDINEA: 0.01M km² 🌊 NEMERTEANS: 0.01M km² 🌊 PLATYHELMINTHS: 0.05M km² 🌊 NEMATODES: 0.1M km² 🌊 ROTIFERS: 0.05M km² 🌊 TARDIGRADES: 0.01M km² 🌊 GASTROTRICHS: 0.01M km² 🌊 KINORHYNCHS: 0.001M km² 🌊 NEMATOMORPHS: 0.001M km² 🌊 ACANTHOCEPHALANS: 0.001M km² 🌊 GNATHOSTOMULIDS: 0.0001M km² 🌊 MICROTURBELLARIANS: 0.001M km² 🌊 MONOGENETICS: 0.001M km² 🌊 DICYEMIDS: 0.0001M km² 🌊 ORTHONECTIDS: 0.0001M km² 🌊 ROXOMONADS: 0.0001M km² 🌊 APUSOMONADS: 0.0001M km² 🌊 BIKONTA: 0.001M km² 🌊 OPISTHOKONTA: 0.01M km² 🌊 AMOEBOZOA: 0.001M km² 🌊 EXCAVATA: 0.001M km² 🌊 SAR: 0.01M km² 🌊 HACROBIA: 0.001M km² 🌊 RHIZARIA: 0.001M km² 🌊 ALVEOLATA: 0.01M km² 🌊 STRAMENOPILES: 0.01M km² 🌊 ARCHAEPLASTIDA: 0.01M km² 🌊 UNIKONTA: 0.01M km² 🌊 EUKARYOTE: 2.5M km² 🌊 CELL: 3M km² 🌊 ORGANISM: 3.5M km² 🌊 LIFE: 4M km² 🌊 BIOSPHERE: 4M km² 🌊 ECOSYSTEM: 4M km² 🌊 BIOME: 4M km² 🌊 HABITAT: 4M km² 🌊 NICHE: 4M km² 🌊 SPECIES: 8.7M estimated 🌊 INDIVIDUAL: 1e30 estimated 🌊 GENE: 1e30 estimated 🌊 DNA: 1e30 estimated 🌊 PROTEIN: 1e30 estimated 🌊 MOLECULE: 1e30 estimated 🌊 ATOM: 1e50 estimated 🌊 ELEMENTARY PARTICLE: 1e80 estimated 🌊 QUARK: 1e100 estimated 🌊 STRING: 1e120 theoretical 🌊 UNIVERSE: 1 observed 🌊 MULTIVERSE: ∞ theoretical 🌊 SIMULATION: 1 running 🌊 REALITY: 1 perceived 🌊 CONSCIOUSNESS: 8.1B human 🌊 INTELLIGENCE: 2.5B AI systems 🌊 KNOWLEDGE: ∞ potential 🌊 INFORMATION: ∞ processed 🌊 DATA: 2.4M PB/sec 🌊 BIT: 0/1 fundamental 🌊 BYTE: 8 bits 🌊 KILOBYTE: 1024 bytes 🌊 MEGABYTE: 1024 KB 🌊 GIGABYTE: 1024 MB 🌊 TERABYTE: 1024 GB 🌊 PETABYTE: 1024 TB 🌊 EXABYTE: 1024 PB 🌊 ZETTABYTE: 1024 EB 🌊 YOTTABYTE: 1024 ZB 🌊 BRONTABYTE: 1024 YB 🌊 GEOPBYTE: 1024 BB 🌊 DOGGONABYTE: 1024 GB 🌊 MEASUREMENT: ∞ possibilities 🌊 SIMULATION: ACTIVE 🟢`;

const secondaryTickerData = `🌐 CONTINENT: ASIA | POP: 4.7B | GDP: $32T | 🌍 AFRICA | POP: 1.4B | GDP: $2.9T | 🌎 EUROPE | POP: 748M | GDP: $22T | 🌎 NORTH AMERICA | POP: 592M | GDP: $28T | 🌎 SOUTH AMERICA | POP: 434M | GDP: $3.5T | 🌏 OCEANIA | POP: 44M | GDP: $1.9T | 🌍 ANTARCTICA | POP: 1,200 | RESEARCH: 4,000 STATIONS | 🌐 LAND USE: AG 38% | FOREST 31% | URBAN 3% | OTHER 28% | 🌊 OCEANS: 71% | 🌍 CLIMATE: +1.2°C ABOVE PRE-INDUSTRIAL | ⚠️ CARBON BUDGET: 500Gt REMAINING (at 1.5°C) | 📈 EMISSIONS: 36.8Gt CO2/YR | 🔄 CARBON CYCLE: 50% ABSORBED BY OCEANS/LAND | 🌿 LAND SINKS: 12Gt/YR | 🌊 OCEAN SINKS: 9Gt/YR | 🏭 INDUSTRIAL: 36Gt/YR | 🚗 TRANSPORT: 7Gt/YR | ⚡ ENERGY: 15Gt/YR | 🏠 BUILDINGS: 6Gt/YR | 🌾 AGRICULTURE: 5Gt/YR | 🗑️ WASTE: 2Gt/YR | 🔥 DEFORESTATION: 3Gt/YR | 🌋 NATURAL: 1Gt/YR | 🌍 NET: +0.5Gt/YR | 📉 TREND: +0.5% ANNUAL GROWTH | 📊 2023 RECORD HIGH | 🎯 PARIS GOAL: -45% BY 2030 | 📉 CURRENT PATH: +2.7°C BY 2100 | 🌡️ 1.5°C BUDGET EXHAUSTED: 2030 | 🌡️ 2.0°C BUDGET EXHAUSTED: 2050 | 🌍 CASCADE EFFECTS: PERMAFROST +300Gt | 🌋 VOLCANIC: +50Gt | 🌊 METHANE CLATHRATES: +1000Gt | 🌋 GEOTHERMAL: +10Gt | 🌋 TECTONIC: +5Gt | 🌊 OCEAN ANOXIA: +200Gt | 🌳 FOREST DIEBACK: +100Gt | 🏜️ DESERTIFICATION: +50Gt | 🌊 WETLAND LOSS: +30Gt | 🏔️ GLACIAL MELT: +20Gt | 🌊 ICE SHEET COLLAPSE: +500Gt | 🌋 SUBMARINE VOLCANISM: +100Gt | 🌋 HYDROTHERMAL: +50Gt | 🌋 SEAFLOOR ERUPTIONS: +20Gt | 🌋 METHANE SEEPS: +200Gt | 🌋 GAS HYDRATES: +1000Gt | 🌊 OCEAN ACIDIFICATION: +100Gt | 🌊 DECOMPOSITION: +50Gt | 🌊 EUTROPHICATION: +30Gt | 🌊 ANOXIA: +200Gt | 🌊 DEAD ZONES: +10Gt | 🌊 UPWELLING: +5Gt | 🌊 CIRCULATION SLOWDOWN: +50Gt | 🌊 THERMOHALINE: +100Gt | 🌊 EL Niño: +20Gt | 🌊 La NIÑA: -10Gt | 🌊 PDO: ±15Gt | 🌊 AMO: ±10Gt | 🌊 SAM: ±5Gt | 🌊 IOD: ±3Gt | 🌊 MJO: ±2Gt | 🌊 QBO: ±1Gt | 🌊 ENSO: ±20Gt | 🌊 PNA: ±5Gt | 🌊 NAO: ±10Gt | 🌊 AO: ±8Gt | 🌊 EAP: ±3Gt | 🌊 WP: ±4Gt | 🌊 EP NP: ±2Gt | 🌊 CP NP: ±1Gt | 🌊 SP: ±1Gt | 🌊 EU: ±2Gt | 🌊 EA: ±3Gt | 🌊 EA/WR: ±2Gt | 🌊 EA/NP: ±1Gt | 🌊 EA/SP: ±1Gt | 🌊 EA/SA: ±0.5Gt | 🌊 EA/SAF: ±0.3Gt | 🌊 EA/AF: ±0.2Gt | 🌊 EA/OC: ±0.1Gt | 🌊 EA/AN: ±0.05Gt | 🌐 SIMULATION TIME ACCURACY: 99.97% | 🖥️ FRAMERATE: 60 FPS | 📊 DATA POINTS PROCESSED: 2.4M PER SECOND | 🧠 AI DECISIONS: 8.2M PER SECOND | 🔮 PREDICTIONS ACTIVE: 1.2M | 📈 MODELS TRAINING: 4,280 | 📊 DATASETS: 1.8M CURATED | 🖼️ IMAGES PROCESSED: 42B DAILY | 🎵 AUDIO PROCESSED: 12B HOURS DAILY | 📹 VIDEO PROCESSED: 8B HOURS DAILY | 📄 DOCUMENTS PROCESSED: 45B DAILY | 📧 EMAILS PROCESSED: 330B DAILY | 💬 CHAT MESSAGES: 520B DAILY | 📱 SMS: 23B DAILY | 📠 FAX: 2M DAILY | 📞 PHONE CALLS: 12B DAILY | 🛰️ SATELLITE DOWNLOADS: 8PB DAILY | 📡 RADAR SCANS: 4M DAILY | 🛩️ FLIGHT TRACKS: 50K ACTIVE | 🚢 SHIP TRACKS: 60K ACTIVE | 🚗 VEHICLE TRACKS: 1.2B ACTIVE | 🚲 BIKE TRACKS: 120M ACTIVE | 🚶 FOOT TRAFFIC: 4.2B ACTIVE | 📊 SENSOR NODES: 45B ACTIVE | 🌡️ TEMPERATURE SENSORS: 12B ACTIVE | 💧 HUMIDITY SENSORS: 8B ACTIVE | 🌬️ AIR QUALITY SENSORS: 4B ACTIVE | 🔊 SOUND SENSORS: 2B ACTIVE | 📹 CAMERA NODES: 1.5B ACTIVE | 🛣️ TRAFFIC CAMERAS: 120M ACTIVE | 🚨 SPEED CAMERAS: 80M ACTIVE | 📹 SECURITY CAMERAS: 400M ACTIVE | 🏠 DOORBELL CAMS: 50M ACTIVE | 🛒 STORE CAMERAS: 200M ACTIVE | 🏦 BANK CAMERAS: 10M ACTIVE | 🏫 SCHOOL CAMERAS: 30M ACTIVE | 🏥 HOSPITAL CAMERAS: 20M ACTIVE | 🏢 OFFICE CAMERAS: 150M ACTIVE | 🏗️ CONSTRUCTION CAMERAS: 15M ACTIVE | 🚓 POLICE CAMERAS: 50M ACTIVE | 🚒 FIRE CAMERAS: 10M ACTIVE | 🚑 AMBULANCE CAMERAS: 5M ACTIVE | 🚗 DASHCAMS: 200M ACTIVE | 🛵 MOTORCYCLE CAMS: 20M ACTIVE | 🚲 BIKE CAMS: 5M ACTIVE | 🛴 SCOOTER CAMS: 2M ACTIVE | 🚁 DRONE CAMS: 500K ACTIVE | 🛰️ SATELLITE IMAGERY: 10PB DAILY | 📷 STREET VIEW: 10M KM IMAGED | 🗺️ MAP UPDATES: 5M DAILY | 🏘️ BUILDING FOOTPRINTS: 1.5B MAPPED | 🏠 ADDRESSES: 1.2B MAPPED | 🛣️ ROADS: 80M KM MAPPED | 🚉 RAILWAYS: 1.2M KM MAPPED | ⛽ GAS STATIONS: 1.5M MAPPED | 🏪 RETAIL STORES: 25M MAPPED | 🏥 HOSPITALS: 200K MAPPED | 🏫 SCHOOLS: 5M MAPPED | 🏛️ GOVERNMENT BUILDINGS: 2M MAPPED | 🏢 OFFICE BUILDINGS: 10M MAPPED | 🏭 FACTORIES: 1M MAPPED | ⛏️ MINES: 100K MAPPED | 🌾 FARMLAND: 5B HA MAPPED | 🌲 FORESTS: 4B HA MAPPED | 🏜️ DESERTS: 1.5B HA MAPPED | 🏔️ MOUNTAINS: 300M HA MAPPED | 🌊 WATER BODIES: 361M KM² MAPPED | 🏝️ ISLANDS: 500K MAPPED | 🌋 VOLCANOES: 1,500 MAPPED | 🌎 COUNTRIES: 195 MAPPED | 🗺️ DISPUTED BORDERS: 50 ACTIVE | 🏙️ CITIES >100K: 10K MAPPED | 🌆 TOWNS: 500K MAPPED | 🏘️ VILLAGES: 5M MAPPED | 🏡 NEIGHBORHOODS: 50M MAPPED | 🏘️ BLOCKS: 500M MAPPED | 🏗️ BUILDINGS: 1.5B 3D MODELED | 🚪 DOORS: 6B MAPPED | 🪟 WINDOWS: 12B MAPPED | 🏠 ROOFS: 1.5B MAPPED | 🌳 TREES: 3B MAPPED | 🌱 BUSHES: 5B MAPPED | 🌾 GRASS: 1.2B HA MAPPED | 🏖️ BEACHES: 200K MAPPED | 🏞️ PARKS: 500K MAPPED | 🏊 POOLS: 10M MAPPED | 🏟️ STADIUMS: 50K MAPPED | 🎡 THEME PARKS: 2K MAPPED | 🏰 CASTLES: 5K MAPPED | 🕌 RELIGIOUS SITES: 1M MAPPED | 🏛️ MONUMENTS: 100K MAPPED | 🗿 STATUES: 500K MAPPED | 🌉 BRIDGES: 1M MAPPED | 🚇 TUNNELS: 1,200 MAPPED | 🚢 PORTS: 2K MAPPED | ✈️ AIRPORTS: 5K MAPPED | 🚉 RAIL STATIONS: 100K MAPPED | 🚌 BUS STATIONS: 500K MAPPED | 🚕 TAXI STANDS: 2M MAPPED | 🅿️ PARKING LOTS: 10M MAPPED | 🚗 PARKING SPOTS: 2B MAPPED | 🚲 BIKE RACKS: 5M MAPPED | 🛵 SCOOTER ZONES: 500K MAPPED | ⛽ GAS STATIONS: 1.5M MAPPED | ⚡ EV CHARGING STATIONS: 2.8M MAPPED | 🚰 WATER FOUNTAINS: 1M MAPPED | 🚽 PUBLIC TOILETS: 2M MAPPED | 🗑️ TRASH CANS: 10M MAPPED | 🚸 SCHOOL ZONES: 500K MAPPED | 🚸 CROSSWALKS: 5M MAPPED | 🚦 TRAFFIC LIGHTS: 10M MAPPED | 🚧 SPEED BUMPS: 2M MAPPED | 🛑 STOP SIGNS: 5M MAPPED | ⚠️ WARNING SIGNS: 8M MAPPED | 📢 SPEAKERS: 1M MAPPED | 🚨 SIRENS: 500K MAPPED | 🔥 HYDRANTS: 10M MAPPED | 🏥 DEFIBRILLATORS: 1M MAPPED | 🚪 FIRE DOORS: 5M MAPPED | 🔥 SMOKE DETECTORS: 50M MAPPED | 🧯 FIRE EXTINGUISHERS: 20M MAPPED | 🚪 EXIT SIGNS: 10M MAPPED | 🛡️ BOMB SHELTERS: 50K MAPPED | 🏠 FALLOUT SHELTERS: 100K MAPPED | 🚨 CIVIL DEFENSE: 10K MAPPED | 🏢 GOVERNMENT BUNKERS: 1K MAPPED | 🛰️ MILITARY BASES: 1K MAPPED | 🚀 LAUNCH SITES: 20 MAPPED | 🛰️ SATELLITE GROUND STATIONS: 200 MAPPED | 📡 RADAR INSTALLATIONS: 1,200 MAPPED | 🕵️ INTELLIGENCE FACILITIES: 100 MAPPED | 🏛️ EMBASSIES: 1,200 MAPPED | 🏦 CENTRAL BANKS: 200 MAPPED | 💎 VAULTS: 500 MAPPED | 🏛️ STOCK EXCHANGES: 48 MAPPED | 🏦 DATA CENTERS: 8,000 MAPPED | 🏭 POWER PLANTS: 62,000 MAPPED | ⛏️ MINES: 100K MAPPED | 🌾 FARMS: 570M MAPPED | 🏘️ SETTLEMENTS: 10M MAPPED | 🏕️ CAMPSITES: 50K MAPPED | 🏖️ BEACHES: 200K MAPPED | 🏞️ PARKS: 500K MAPPED | 🏔️ MOUNTAIN SUMMITS: 100K MAPPED | 🌋 VOLCANIC CRATERS: 1,500 MAPPED | 🌊 OCEAN TRENCHES: 50 MAPPED | 🏜️ DESERT OASES: 500 MAPPED | 🌲 CAVES: 50K MAPPED | 🕳️ SINKHOLES: 10K MAPPED | 🌋 GEYSERS: 1,000 MAPPED | 🌋 HOT SPRINGS: 10K MAPPED | 🌊 WATERFALLS: 5K MAPPED | 🌊 RAPIDS: 2K MAPPED | 🌊 FJORDS: 1K MAPPED | 🌊 ESTUARIES: 500 MAPPED | 🌊 DELTAS: 300 MAPPED | 🌊 LAGOONS: 1K MAPPED | 🌊 COASTLINES: 1.6M KM MAPPED | 🌊 ISLANDS: 500K MAPPED | 🌊 REEFS: 3K MAPPED | 🌊 SEAMOUNTS: 100K MAPPED | 🌊 ABYSSAL PLAINS: 50 MAPPED | 🌊 MID-OCEAN RIDGES: 65,000 KM MAPPED | 🌊 SUBMARINE VOLCANOES: 1M ESTIMATED | 🌊 HYDROTHERMAL VENTS: 500 MAPPED | 🌊 COLD SEEPS: 200 MAPPED | 🌊 GAS HYDRATES: 100 SITES MAPPED | 🌊 METHANE BUBBLES: 50 SITES MAPPED | 🌊 OCEAN GYRES: 5 MAJOR | 🌊 EDDIES: 10K DAILY | 🌊 TIDES: 1,000 STATIONS | 🌊 CURRENTS: 100 MAJOR | 🌊 UPWELLINGS: 50 MAJOR | 🌊 SEA ICE: 15M KM² SEASONAL | 🌊 ICEBERGS: 10K TRACKED DAILY | 🌊 GLACIERS: 200K MAPPED | 🌊 ICE SHEETS: 2 MAJOR | 🌊 ICE CAPS: 50 MAJOR | 🌊 PERMAFROST: 24% LAND | 🌊 SNOW COVER: 46M KM² SEASONAL | 🌊 FROZEN LAKES: 14M SEASONAL | 🌊 FROZEN RIVERS: 2M KM SEASONAL | 🌊 FROZEN SOIL: 25% LAND | 🌊 ACTIVE LAYER: 0.5-2M DEPTH | 🌊 THERMOKARST: 1M SITES | 🌊 PINGO: 10K SITES | 🌊 PALSAS: 5K SITES | 🌊 LITHALS: 1K SITES | 🌊 STRANDED ICE: 100K SITES | 🌊 GLACIAL LAKES: 150K MAPPED | 🌊 PROGLACIAL LAKES: 5K MAPPED | 🌊 MORAINES: 100K MAPPED | 🌊 DRUMLINS: 1M MAPPED | 🌊 ESKERS: 50K MAPPED | 🌊 KAMES: 10K MAPPED | 🌊 ERRATICS: 100K MAPPED | 🌊 ROCK BASINS: 10K MAPPED | 🌊 CIRCQUES: 10K MAPPED | 🌊 ARÊTES: 5K MAPPED | 🌊 HORNS: 1K MAPPED | 🌊 U-SHAPED VALLEYS: 10K MAPPED | 🌊 HANGING VALLEYS: 5K MAPPED | 🌊 TRUNCATED SPURS: 5K MAPPED | 🌊 STEPS: 1K MAPPED | 🌊 POTHOLES: 10K MAPPED | 🌊 GULLIES: 100K MAPPED | 🌊 RAVINES: 50K MAPPED | 🌊 CANYONS: 1K MAJOR | 🌊 WADIS: 10K MAPPED | 🌊 ARROYOS: 5K MAPPED | 🌊 DRY GULLIES: 50K MAPPED | 🌊 BADLANDS: 1M HA MAPPED | 🌊 DESERT PAVEMENT: 1B M² MAPPED | 🌊 YARDANGS: 10K MAPPED | 🌊 DUNES: 2M KM² MAPPED | 🌊 SALT FLATS: 100K KM² MAPPED | 🌊 PLAYAS: 1K MAPPED | 🌊 SABKHA: 500 MAPPED | 🌊 TEPEES: 100 MAPPED | 🌊 HOODOOS: 1K MAPPED | 🌊 INSHORE ISLANDS: 50K MAPPED | 🌊 OCEANIC ISLANDS: 10K MAPPED | 🌊 ATOLLS: 400 MAPPED | 🌊 VOLCANIC ISLANDS: 2K MAPPED | 🌊 CONTINENTAL ISLANDS: 50K MAPPED | 🌊 ARTIFICIAL ISLANDS: 500 MAPPED | 🌊 RIVER ISLANDS: 10K MAPPED | 🌊 LAKE ISLANDS: 5K MAPPED | 🌊 TIDAL ISLANDS: 1K MAPPED | 🌊 SUBAERIAL ISLANDS: 100 MAPPED | 🌊 SUBMARINE MOUNTAINS: 100K MAPPED | 🌊 GUYOTS: 1K MAPPED | 🌊 OCEANIC PLATEAUS: 50 MAPPED | 🌊 ABYSSAL HILLS: 1M MAPPED | 🌊 MID-OCEAN RIDGES: 65,000 KM MAPPED | 🌊 TRANSFORM FAULTS: 1,000 MAPPED | 🌊 SUBDUCTION ZONES: 50 MAPPED | 🌊 RIFT VALLEYS: 50 MAPPED | 🌊 HOTSPOTS: 40 MAPPED | 🌊 PLUME TRACKS: 100 MAPPED | 🌊 MICROPLATES: 100 MAPPED | 🌊 OROGENIC BELTS: 50 MAPPED | 🌊 CRATONS: 35 MAPPED | 🌊 SHIELDS: 10 MAJOR | 🌊 PLATFORMS: 20 MAJOR | 🌊 BASINS: 100 MAJOR | 🌊 TROUGHES: 50 MAJOR | 🌊 RIDGES: 100 MAJOR | 🌊 PLATEAUS: 50 MAJOR | 🌊 MOUNTAIN RANGES: 100 MAJOR | 🌊 VOLCANIC ARCS: 30 MAJOR | 🌊 CONTINENTAL MARGINS: 50 MAPPED | 🌊 PASSIVE MARGINS: 30 MAPPED | 🌊 ACTIVE MARGINS: 20 MAPPED | 🌊 TRANSFORM MARGINS: 10 MAPPED | 🌊 OCEANIC TRENCHES: 50 MAPPED | 🌊 ISLAND ARCS: 30 MAPPED | 🌊 CONTINENTAL ARCS: 10 MAPPED | 🌊 BACK-ARC BASINS: 20 MAPPED | 🌊 FOREARC BASINS: 30 MAPPED | 🌊 ACCRETIONARY WEDGES: 40 MAPPED | 🌊 SUBDUCTION COMPLEXES: 50 MAPPED | 🌊 OPHIOLITES: 100 MAPPED | 🌊 MÉLANGE: 50 MAPPED | 🌊 SERPENTINITE: 200 MAPPED | 🌊 METAMORPHIC CORES: 50 MAPPED | 🌊 GRANITOID BATHOLITHS: 100 MAPPED | 🌊 VOLCANIC PLATEAUS: 50 MAPPED | 🌊 LARGE IGNEOUS PROVINCES: 10 MAPPED | 🌊 GRABENS: 100 MAPPED | 🌊 HORSTS: 100 MAPPED | 🌊 STEP FAULTS: 200 MAPPED | 🌊 DETACHMENT FAULTS: 50 MAPPED | 🌊 THRUST FAULTS: 500 MAPPED | 🌊 STRIKE-SLIP FAULTS: 1,000 MAPPED | 🌊 NORMAL FAULTS: 1,000 MAPPED | 🌊 REVERSE FAULTS: 500 MAPPED | 🌊 OBLIQUE FAULTS: 200 MAPPED | 🌊 DÉCOLLEMENTS: 50 MAPPED | 🌊 SHEAR ZONES: 100 MAPPED | 🌊 MYLONITE ZONES: 50 MAPPED | 🌊 CATACLASITE ZONES: 50 MAPPED | 🌊 GOUGE ZONES: 100 MAPPED | 🌊 FAIRWAYS: 50 MAPPED | 🌊 STRIATIONS: 1K MAPPED | 🌊 RIESEL: 10 MAPPED | 🌊 ROSS: 5 MAPPED | 🌊 SCHISTOSITY: 100 MAPPED | 🌊 GNEISSOSITY: 50 MAPPED | 🌊 LINEATION: 200 MAPPED | 🌊 FOLIATION: 500 MAPPED | 🌊 BEDDING: 1M SITES | 🌊 LAMINATION: 1M SITES | 🌊 CROSS-BEDDING: 100K SITES | 🌊 GRADED BEDDING: 50K SITES | 🌊 RIPPLES: 1M SITES | 🌊 EOLIAN LANDFORMS: 5M SITES | 🌊 LOESS: 10M KM² | 🌊 SAND SHEETS: 1M KM² | 🌊 GYPSUM DUNES: 10K KM² | 🌊 SALT DUNES: 5K KM² | 🌊 CLAY DUNES: 1K KM² | 🌊 GRAVEL DUNES: 100 KM² | 🌊 LAVA DUNES: 10 KM² | 🌊 MUD DUNES: 50 KM² | 🌊 CORAL DUNES: 5 KM² | 🌊 OYSTER DUNES: 1 KM² | 🌊 SHELL DUNES: 10 KM² | 🌊 VOLCANIC ASH DUNES: 100 KM² | 🌊 GLACIAL OUTWASH DUNES: 500 KM² | 🌊 PERMAFROST DUNES: 50 KM² | 🌊 DESERT PAVEMENT: 1B M² | 🌊 REG: 500K KM² | 🌊 HAMADA: 100K KM² | 🌊 SERIR: 200K KM² | 🌊 ERG: 2M KM² | 🌊 SABKHA: 500K KM² | 🌊 CHOTT: 50K KM² | 🌊 PLAYAS: 100K KM² | 🌊 SALARS: 10K KM² | 🌊 SALINAS: 5K KM² | 🌊 TAFONI: 10K SITES | 🌊 TOR: 1K SITES | 🌊 KOPPIE: 10K SITES | 🌊 INSULATED HILLS: 1K SITES | 🌊 NESKAN: 100 SITES | 🌊 PAN: 10K SITES | 🌊 VLEI: 1K SITES | 🌊 BAI: 100 SITES | 🌊 BLINKWATER: 50 SITES | 🌊 GORGE: 5K SITES | 🌊 CLIFF: 10K SITES | 🌊 ESCARPMENT: 5K SITES | 🌊 BUTTE: 1K SITES | 🌊 MESA: 500 SITES | 🌊 PLATEAU: 1K SITES | 🌊 TABLEMOUNTAIN: 100 SITES | 🌊 CUESTA: 200 SITES | 🌊 HOMOCLINE: 100 SITES | 🌊 SYNCLINE: 1K SITES | 🌊 ANTICLINE: 1K SITES | 🌊 MONOCLINE: 200 SITES | 🌊 DRUM: 50 SITES | 🌊 BASIN: 1K SITES | 🌊 BOWL: 500 SITES | 🌊 AMPHITHEATER: 100 SITES | 🌊 CALDERA: 100 SITES | 🌊 MAAR: 100 SITES | 🌊 TUFF RING: 50 SITES | 🌊 LAVA DOME: 200 SITES | 🌊 SHIELD VOLCANO: 500 SITES | 🌊 STRATOVOLCANO: 1K SITES | 🌊 COMPLEX VOLCANO: 200 SITES | 🌊 SUBGLACIAL VOLCANO: 100 SITES | 🌊 SUBMARINE VOLCANO: 1M ESTIMATED | 🌊 HYDROTHERMAL VENT FIELD: 100 SITES | 🌊 COLD SEEP FIELD: 50 SITES | 🌊 BRINE POOL FIELD: 20 SITES | 🌊 OIL SEEP FIELD: 100 SITES | 🌊 GAS SEEP FIELD: 200 SITES | 🌊 METHANE SEEP FIELD: 50 SITES | 🌊 CARBONATE SEQUENCE: 50 SITES | 🌊 SALT TECTONICS: 50 SITES | 🌊 MUD VOLCANO: 100 SITES | 🌊 SALT GLACIAL: 10 SITES | 🌊 SALT PAN: 1K SITES | 🌊 SALT FLAT: 500 SITES | 🌊 SALINA: 100 SITES | 🌊 COASTAL LAGOON: 1K SITES | 🌊 ESTUARY: 1K SITES | 🌊 DELTA: 500 SITES | 🌊 FJORD: 1K SITES | 🌊 RIA: 500 SITES | 🌊 CALANQUE: 100 SITES | 🌊 FIORD: 1K SITES | 🌊 SOUND: 500 SITES | 🌊 STRAIT: 500 SITES | 🌊 CHANNEL: 1K SITES | 🌊 PASSAGE: 1K SITES | 🌊 CANAL: 100 SITES | 🌊 SLICK: 10 SITES | 🌊 SLOUGH: 500 SITES | 🌊 MARSH: 1M HA | 🌊 SWAMP: 500K HA | 🌊 BOG: 200K HA | 🌊 FEN: 100K HA | 🌊 MIRE: 50K HA | 🌊 QUAGMIRE: 10K HA | 🌊 PEATLAND: 4M HA | 🌊 WETLAND: 12M KM² | 🌊 FLOODPLAIN: 2M KM² | 🌊 ALLUVIAL FAN: 100K SITES | 🌊 CONE: 1K SITES | 🌊 TALUS SLOPE: 10K SITES | 🌊 COLLUVIUM: 1M HA | 🌊 ELUVIUM: 500K HA | 🌊 REGOLITH: 100M KM² | 🌊 SOIL: 150M KM² | 🌊 LITHOSOL: 10M KM² | 🌊 ARENOSOL: 20M KM² | 🌊 LUVISOL: 15M KM² | 🌊 PHAEOZEM: 5M KM² | 🌊 CHERNOZEM: 2M KM² | 🌊 VERTISOL: 3M KM² | 🌊 PODZOL: 10M KM² | 🌊 GLEYSOL: 5M KM² | 🌊 PLANTSOL: 1M KM² | 🌊 HISTOSOL: 4M HA | 🌊 ANDOSOL: 2M KM² | 🌊 FERRALSOL: 5M KM² | 🌊 ACRISOL: 8M KM² | 🌊 LIXISOL: 3M KM² | 🌊 RENIC EPIDOSOL: 2M KM² | 🌊 NITISOL: 1M KM² | 🌊 KASTANOZEM: 1M KM² | 🌊 GREYXEM: 1M KM² | 🌊 SOLONETZ: 2M KM² | 🌊 SOLONCHAK: 1M KM² | 🌊 GYPSISOL: 1M KM² | 🌊 CALCISOL: 2M KM² | 🌊 LEPTOSOL: 10M KM² | 🌊 REGOSOL: 5M KM² | 🌊 FLUVISOL: 5M KM² | 🌊 ANTHROSOL: 2M KM² | 🌊 TECHNOSOL: 0.1M KM² | 🌊 CRYOSOL: 5M KM² | 🌊 PALSASOL: 0.5M KM² | 🌊 TURF: 0.5M KM² | 🌊 PEAT: 4M HA | 🌊 TURBA: 1M HA | 🌊 FIBRIST: 0.5M HA | 🌊 HEMIST: 1M HA | 🌊 SAPRIST: 0.5M HA | 🌊 MUCKVAPOR: 0.1M HA | 🌊 MUCK: 0.5M HA | 🌊 PEATY MUCK: 0.2M HA | 🌊 ORGANIC SOIL: 5M HA | 🌊 MINERAL SOIL: 145M KM² | 🌊 BEDROCK: 100M KM² | 🌊 WEATHERED ROCK: 50M KM² | 🌊 SAPROLITE: 20M KM² | 🌊 TALUS: 5M KM² | 🌊 COLLUVIUM: 10M KM² | 🌊 ELUVIUM: 5M KM² | 🌊 ALLUVIUM: 20M KM² | 🌊 LACUSTRINE: 5M KM² | 🌊 MARINE: 10M KM² | 🌊 EOLIAN: 5M KM² | 🌊 GLACIAL: 10M KM² | 🌊 PERIGLACIAL: 5M KM² | 🌊 FLUVIAL: 30M KM² | 🌊 KARST: 2M KM² | 🌊 VULCANIC: 1M KM² | 🌊 IMPACT: 0.1M KM² | 🌊 ANTHROPOGENIC: 5M KM² | 🌊 URBAN: 1M KM² | 🌊 AGRICULTURAL: 50M KM² | 🌊 FOREST: 40M KM² | 🌊 GRASSLAND: 30M KM² | 🌊 SHRUBLAND: 10M KM² | 🌊 SAVANNA: 20M KM² | 🌊 TUNDRA: 5M KM² | 🌊 DESERT: 15M KM² | 🌊 ICE: 15M KM² | 🌊 WATER: 361M KM² | 🌊 WETLAND: 12M KM² | 🌊 MANGROVE: 0.2M KM² | 🌊 SEAGRASS: 0.3M KM² | 🌊 CORAL REEF: 0.3M KM² | 🌊 KELP: 0.05M KM² | 🌊 MACROALGAE: 0.1M KM² | 🌊 SEAGRASS MEADOW: 0.3M KM² | 🌊 TURF: 0.5M KM² | 🌊 MOSS: 1M KM² | 🌊 LICHEN: 0.5M KM² | 🌊 CRYPTGAMIC: 0.2M KM² | 🌊 ALGAE: 0.1M KM² | 🌊 CYANOBACTERIA: 0.05M KM² | 🌊 PLANKTON: 0.01M KM² | 🌊 ZOOPLANKTON: 0.01M KM² | 🌊 BACTERIA: 0.001M KM² | 🌊 VIRUSES: 0.0001M KM² | 🌊 ARCHAEA: 0.0005M KM² | 🌊 FUNGI: 0.1M KM² | 🌊 PROTISTS: 0.01M KM² | 🌊 MICROFAUNA: 0.01M KM² | 🌊 NEMATODES: 0.1M KM² | 🌊 ROTIFERS: 0.05M KM² | 🌊 TARDIGRADES: 0.01M KM² | 🌊 MITES: 0.1M KM² | 🌊 SPRINGTAILS: 0.1M KM² | 🌊 DIPLURANS: 0.05M KM² | 🌊 PROTURANS: 0.05M KM² | 🌊 CENTIPEDES: 0.1M KM² | 🌊 MILLIPEDES: 0.1M KM² | 🌊 SPIDERS: 0.1M KM² | 🌊 SCORPIONS: 0.05M KM² | 🌊 PSEUDOSCORPIONS: 0.01M KM² | 🌊 HARVESTMEN: 0.05M KM² | 🌊 TICKS: 0.1M KM² | 🌊 INSECTS: 5M KM² | 🌊 BEETLES: 1M KM² | 🌊 BUTTERFLIES: 0.1M KM² | 🌊 MOTHS: 0.2M KM² | 🌊 FLIES: 0.5M KM² | 🌊 MOSQUITOES: 0.2M KM² | 🌊 BEES: 0.1M KM² | 🌊 WASPS: 0.1M KM² | 🌊 ANTS: 0.3M KM² | 🌊 TERMITES: 0.1M KM² | 🌊 GRASSHOPPERS: 0.1M KM² | 🌊 CRICKETS: 0.05M KM² | 🌊 COCKROACHES: 0.1M KM² | 🌊 BUGS: 0.2M KM² | 🌊 APHIDS: 0.05M KM² | 🌊 SCALE INSECTS: 0.05M KM² | 🌊 WHITEFLIES: 0.02M KM² | 🌊 THRIPS: 0.01M KM² | 🌊 LICE: 0.05M KM² | 🌊 FLEAS: 0.02M KM² | 🌊 CRUSTACEANS: 0.2M KM² | 🌊 COPEPODS: 0.1M KM² | 🌊 CLADOCERANS: 0.05M KM² | 🌊 OSTRACODS: 0.02M KM² | 🌊 AMPHIPODS: 0.05M KM² | 🌊 ISOPODS: 0.05M KM² | 🌊 DECAPODS: 0.1M KM² | 🌊 BRANCHIOPODS: 0.02M KM² | 🌊 CEPHALOPODS: 0.05M KM² | 🌊 GASTROPODS: 0.1M KM² | 🌊 BIVALVES: 0.1M KM² | 🌊 POLYCHAETES: 0.05M KM² | 🌊 OLIGOCHAETES: 0.05M KM² | 🌊 HIRUDINEA: 0.01M KM² | 🌊 NEMERTEANS: 0.01M KM² | 🌊 PLATYHELMINTHS: 0.05M KM² | 🌊 NEMATODES: 0.1M KM² | 🌊 ROTIFERS: 0.05M KM² | 🌊 TARDIGRADES: 0.01M KM² | 🌊 GASTROTRICHS: 0.01M KM² | 🌊 KINORHYNCHS: 0.001M KM² | 🌊 NEMATOMORPHS: 0.001M KM² | 🌊 ACANTHOCEPHALANS: 0.001M KM² | 🌊 GNATHOSTOMULIDS: 0.0001M KM² | 🌊 MICROTURBELLARIANS: 0.001M KM² | 🌊 MONOGENETICS: 0.001M KM² | 🌊 DICYEMIDS: 0.0001M KM² | 🌊 ORTHONECTIDS: 0.0001M KM² | 🌊 ROXOMONADS: 0.0001M KM² | 🌊 APUSOMONADS: 0.0001M KM² | 🌊 BIKONTA: 0.001M KM² | 🌊 OPISTHOKONTA: 0.01M KM² | 🌊 AMOEBOZOA: 0.001M KM² | 🌊 EXCAVATA: 0.001M KM² | 🌊 SAR: 0.01M KM² | 🌊 HACROBIA: 0.001M KM² | 🌊 RHIZARIA: 0.001M KM² | 🌊 ALVEOLATA: 0.01M KM² | 🌊 STRAMENOPILES: 0.01M KM² | 🌊 ARCHAEPLASTIDA: 0.01M KM² | 🌊 UNIKONTA: 0.01M KM² | 🌊 EUKARYOTE: 2.5M KM² | 🌊 CELL: 3M KM² | 🌊 ORGANISM: 3.5M KM² | 🌊 LIFE: 4M KM² | 🌊 BIOSPHERE: 4M KM² | 🌊 ECOSYSTEM: 4M KM² | 🌊 BIOME: 4M KM² | 🌊 HABITAT: 4M KM² | 🌊 NICHE: 4M KM² | 🌊 SPECIES: 8.7M ESTIMATED | 🌊 INDIVIDUAL: 1E30 ESTIMATED | 🌊 GENE: 1E30 ESTIMATED | 🌊 DNA: 1E30 ESTIMATED | 🌊 PROTEIN: 1E30 ESTIMATED | 🌊 MOLECULE: 1E30 ESTIMATED | 🌊 ATOM: 1E50 ESTIMATED | 🌊 ELEMENTARY PARTICLE: 1E80 ESTIMATED | 🌊 QUARK: 1E100 ESTIMATED | 🌊 STRING: 1E120 THEORETICAL | 🌊 UNIVERSE: 1 OBSERVED | 🌊 MULTIVERSE: ∞ THEORETICAL | 🌊 SIMULATION: 1 RUNNING | 🌊 REALITY: 1 PERCEIVED | 🌊 CONSCIOUSNESS: 8.1B HUMAN | 🌊 INTELLIGENCE: 2.5B AI SYSTEMS | 🌊 KNOWLEDGE: ∞ POTENTIAL | 🌊 INFORMATION: ∞ PROCESSED | 🌊 DATA: 2.4M PB/SEC | 🌊 BIT: 0/1 FUNDAMENTAL | 🌊 BYTE: 8 BITS | 🌊 KILOBYTE: 1024 BYTES | 🌊 MEGABYTE: 1024 KB | 🌊 GIGABYTE: 1024 MB | 🌊 TERABYTE: 1024 GB | 🌊 PETABYTE: 1024 TB | 🌊 EXABYTE: 1024 PB | 🌊 ZETTABYTE: 1024 EB | 🌊 YOTTABYTE: 1024 ZB | 🌊 BRONTABYTE: 1024 YB | 🌊 GEOPBYTE: 1024 BB | 🌊 DOGGONABYTE: 1024 GB | 🌊 MEASUREMENT: ∞ POSSIBILITIES | 🌊 SIMULATION STATUS: ACTIVE 🟢`;

// Sample data for dynamic elements
const earthquakeData = [
  { mag: 5.2, location: 'Japan', time: '2h ago' },
  { mag: 5.8, location: 'Indonesia', time: '3h ago' },
  { mag: 5.1, location: 'Chile', time: '5h ago' },
  { mag: 5.5, location: 'California', time: '6h ago' },
  { mag: 5.3, location: 'Papua New Guinea', time: '8h ago' },
];

const volcanoData = [
  { name: 'Kilauea', status: 'Erupting', alert: 'Orange' },
  { name: 'Mount Etna', status: 'Active', alert: 'Orange' },
  { name: 'Sakurajima', status: 'Erupting', alert: 'Red' },
  { name: 'Stromboli', status: 'Active', alert: 'Orange' },
  { name: 'Piton de la Fournaise', status: 'Erupting', alert: 'Orange' },
];

const conflictData = [
  { region: 'Ukraine', intensity: 'High', casualties: 'High' },
  { region: 'Middle East', intensity: 'High', casualties: 'High' },
  { region: 'Sahel', intensity: 'Medium', casualties: 'Medium' },
  { region: 'Myanmar', intensity: 'Medium', casualties: 'Medium' },
  { region: 'Ethiopia', intensity: 'Low', casualties: 'Low' },
];

const regions = [
  { name: 'Asia', pop: '4.7B', gdp: '$32T', res: 'High', cli: 'Tropical', trd: 'High', hlth: 'Medium', edu: 'Medium', infra: 'Medium', energy: 'High', env: 'Poor', conflict: 'Medium', urban: '50%', density: '100/km²', growth: '+1.2%' },
  { name: 'Africa', pop: '1.4B', gdp: '$2.9T', res: 'Medium', cli: 'Equatorial', trd: 'Low', hlth: 'Low', edu: 'Low', infra: 'Low', energy: 'Low', env: 'Poor', conflict: 'High', urban: '43%', density: '45/km²', growth: '+2.6%' },
  { name: 'Europe', pop: '748M', gdp: '$22T', res: 'Low', cli: 'Temperate', trd: 'High', hlth: 'High', edu: 'High', infra: 'High', energy: 'Medium', env: 'Good', conflict: 'Low', urban: '75%', density: '72/km²', growth: '+0.3%' },
  { name: 'North America', pop: '592M', gdp: '$28T', res: 'Medium', cli: 'Temperate', trd: 'High', hlth: 'High', edu: 'High', infra: 'High', energy: 'High', env: 'Medium', conflict: 'Low', urban: '82%', density: '35/km²', growth: '+0.8%' },
  { name: 'South America', pop: '434M', gdp: '$3.5T', res: 'Medium', cli: 'Tropical', trd: 'Medium', hlth: 'Medium', edu: 'Medium', infra: 'Medium', energy: 'Medium', env: 'Medium', conflict: 'Low', urban: '80%', density: '25/km²', growth: '+1.1%' },
  { name: 'Oceania', pop: '44M', gdp: '$1.9T', res: 'Low', cli: 'Varied', trd: 'Medium', hlth: 'High', edu: 'High', infra: 'Medium', energy: 'Medium', env: 'Good', conflict: 'Low', urban: '68%', density: '5/km²', growth: '+1.4%' },
  { name: 'Antarctica', pop: '1,200', gdp: 'N/A', res: 'None', cli: 'Polar', trd: 'None', hlth: 'N/A', edu: 'N/A', infra: 'Minimal', energy: 'None', env: 'Pristine', conflict: 'None', urban: '0%', density: '0.0001/km²', growth: '0%' },
];

// Initialize when DOM is ready
document.addEventListener('DOMContentLoaded', function() {
  initializeDashboard();
});

function initializeDashboard() {
  // Hide loading overlay after a delay
  setTimeout(() => {
    const loadingOverlay = document.getElementById('loading-overlay');
    const progressBar = document.getElementById('progress-bar');
    const loadingStatus = document.getElementById('loading-status');
    
    // Simulate loading progress
    let progress = 0;
    const loadingSteps = [
      'Loading tectonic data...',
      'Loading climate data...',
      'Loading population data...',
      'Loading economic data...',
      'Loading environmental data...',
      'Initializing globe...',
      'Calibrating sensors...',
      'Starting simulation...'
    ];
    
    let stepIndex = 0;
    const progressInterval = setInterval(() => {
      progress += Math.random() * 15;
      if (progress > 100) progress = 100;
      progressBar.style.width = `${progress}%`;
      
      if (progress > (stepIndex + 1) * (100 / loadingSteps.length) && stepIndex < loadingSteps.length - 1) {
        stepIndex++;
        loadingStatus.textContent = loadingSteps[stepIndex];
      }
      
      if (progress >= 100) {
        clearInterval(progressInterval);
        setTimeout(() => {
          loadingOverlay.classList.add('hidden');
          startSimulation();
        }, 500);
      }
    }, 200);
  }, 1000);
}

function startSimulation() {
  // Populate tickers
  populateTickers();
  
  // Populate lists
  populateEarthquakes();
  populateVolcanoes();
  populateConflicts();
  
  // Generate charts
  generateTradeRoutes();
  generateAgePyramid();
  generateReligionChart();
  
  // Populate detailed table
  populateDetailedTable();
  
  // Start data refresh interval
  state.dataRefreshInterval = setInterval(updateData, 5000);
  
  // Start simulation time
  updateSimulationTime();
  setInterval(updateSimulationTime, 1000);
  
  // Initialize globe
  initializeGlobe();
  
  // Setup tab switching
  setupTabSwitching();
}

function populateTickers() {
  const globalTicker = document.getElementById('global-ticker-content');
  const secondaryTicker = document.getElementById('secondary-ticker-content');
  
  // Duplicate content for seamless loop
  globalTicker.innerHTML = globalTickerData + globalTickerData;
  secondaryTicker.innerHTML = secondaryTickerData + secondaryTickerData;
  
  // Start ticker animation
  animateTicker(globalTicker, 120000);
  animateTicker(secondaryTicker, 180000);
}

function animateTicker(element, duration) {
  let startTime = null;
  
  function animate(timestamp) {
    if (!startTime) startTime = timestamp;
    const progress = timestamp - startTime;
    const percentage = (progress % duration) / duration;
    
    element.style.transform = `translateX(-${percentage * 50}%)`;
    
    requestAnimationFrame(animate);
  }
  
  requestAnimationFrame(animate);
}

function populateEarthquakes() {
  const list = document.getElementById('earthquake-list');
  list.innerHTML = earthquakeData.map(eq => `
    <li>
      <span>M${eq.mag} - ${eq.location}</span>
      <span>${eq.time}</span>
    </li>
  `).join('');
}

function populateVolcanoes() {
  const list = document.getElementById('volcano-list');
  list.innerHTML = volcanoData.map(v => `
    <li>
      <span>${v.name}</span>
      <span style="color: ${v.alert === 'Red' ? '#ef4444' : '#fbbf24'}">${v.status}</span>
    </li>
  `).join('');
}

function populateConflicts() {
  const list = document.getElementById('conflict-list');
  list.innerHTML = conflictData.map(c => `
    <li>
      <span>${c.region}</span>
      <span style="color: ${c.intensity === 'High' ? '#ef4444' : c.intensity === 'Medium' ? '#fbbf24' : '#10b981'}">${c.intensity}</span>
    </li>
  `).join('');
}

function generateTradeRoutes() {
  const svg = document.getElementById('trade-svg');
  if (!svg) return;
  
  // Simple trade route visualization
  const routes = [
    { x1: 20, y1: 30, x2: 80, y2: 20, volume: 'high' },
    { x1: 80, y1: 20, x2: 30, y2: 70, volume: 'medium' },
    { x1: 30, y1: 70, x2: 70, y2: 40, volume: 'low' },
    { x1: 70, y1: 40, x2: 50, y2: 60, volume: 'high' },
    { x1: 50, y1: 60, x2: 20, y2: 30, volume: 'medium' },
  ];
  
  svg.innerHTML = routes.map(route => `
    <line x1="${route.x1}" y1="${route.y1}" x2="${route.x2}" y2="${route.y2}" 
          stroke="${route.volume === 'high' ? '#ff6b6b' : route.volume === 'medium' ? '#ffd93d' : '#6bcf7f'}"
          stroke-width="${route.volume === 'high' ? 3 : route.volume === 'medium' ? 2 : 1}"
          opacity="0.7">
      <animate attributeName="stroke-dasharray" values="0,100;100,0" dur="3s" repeatCount="indefinite" />
    </line>
  `).join('');
}

function generateAgePyramid() {
  const container = document.getElementById('age-pyramid');
  if (!container) return;
  
  const ageGroups = [
    { age: '0-14', male: 25, female: 24 },
    { age: '15-24', male: 16, female: 15 },
    { age: '25-54', male: 40, female: 39 },
    { age: '55-64', male: 12, female: 13 },
    { age: '65+', male: 7, female: 9 },
  ];
  
  let html = '<svg viewBox="0 0 100 100" style="width:100%;height:100%">';
  
  ageGroups.forEach((group, i) => {
    const y = i * 20;
    const maleWidth = group.male * 0.8;
    const femaleWidth = group.female * 0.8;
    
    html += `
      <text x="5" y="${y + 12}" font-size="4" fill="#94a3b8">${group.age}</text>
      <rect x="10" y="${y}" width="${maleWidth}" height="16" fill="#38bdf8" opacity="0.7"/>
      <rect x="${100 - 10 - femaleWidth}" y="${y}" width="${femaleWidth}" height="16" fill="#f472b6" opacity="0.7"/>
      <text x="${10 + maleWidth + 2}" y="${y + 12}" font-size="3" fill="#94a3b8">${group.male}%</text>
      <text x="${100 - 10 - femaleWidth - 15}" y="${y + 12}" font-size="3" fill="#94a3b8">${group.female}%</text>
    `;
  });
  
  html += '</svg>';
  container.innerHTML = html;
}

function generateReligionChart() {
  const container = document.getElementById('religion-chart');
  if (!container) return;
  
  const religions = [
    { name: 'Christianity', pct: 31, color: '#38bdf8' },
    { name: 'Islam', pct: 25, color: '#fbbf24' },
    { name: 'Hinduism', pct: 15, color: '#f472b6' },
    { name: 'Buddhism', pct: 7, color: '#a78bfa' },
    { name: 'Folk', pct: 6, color: '#34d399' },
    { name: 'Unaff.', pct: 16, color: '#94a3b8' },
  ];
  
  let html = '<svg viewBox="0 0 100 100" style="width:100%;height:100%">';
  
  let currentAngle = 0;
  religions.forEach(rel => {
    const angle = (rel.pct / 100) * 360;
    const largeArc = angle > 180 ? 1 : 0;
    const endAngle = currentAngle + angle;
    
    const x1 = 50 + 40 * Math.cos(Math.PI * currentAngle / 180);
    const y1 = 50 + 40 * Math.sin(Math.PI * currentAngle / 180);
    const x2 = 50 + 40 * Math.cos(Math.PI * endAngle / 180);
    const y2 = 50 + 40 * Math.sin(Math.PI * endAngle / 180);
    
    html += `
      <path d="M 50 50 L ${x1} ${y1} A 40 40 0 ${largeArc} 1 ${x2} ${y2} Z"
            fill="${rel.color}" opacity="0.7">
        <title>${rel.name}: ${rel.pct}%</title>
      </path>
    `;
    
    currentAngle = endAngle;
  });
  
  html += '</svg>';
  container.innerHTML = html;
}

function populateDetailedTable() {
  const tbody = document.getElementById('detailed-table-body');
  if (!tbody) return;
  
  tbody.innerHTML = regions.map(region => `
    <tr>
      <td class="sticky-col"><strong>${region.name}</strong></td>
      <td>${region.pop}</td>
      <td>${region.gdp}</td>
      <td>${region.res}</td>
      <td>${region.cli}</td>
      <td>${region.trd}</td>
      <td>${region.hlth}</td>
      <td>${region.edu}</td>
      <td>${region.infra}</td>
      <td>${region.energy}</td>
      <td>${region.env}</td>
      <td>${region.conflict}</td>
      <td>${region.urban}</td>
      <td>${region.density}</td>
      <td>${region.growth}</td>
    </tr>
  `).join('');
}

function updateData() {
  // Simulate data updates with small random changes
  const updateValue = (id, baseValue, variation = 0.01) => {
    const elem = document.getElementById(id);
    if (elem) {
      const current = parseFloat(elem.textContent.replace(/[^0-9.-]/g, ''));
      const change = (Math.random() - 0.5) * baseValue * variation;
      const newValue = Math.max(0, current + change);
      
      if (id.includes('pop') || id.includes('count')) {
        elem.textContent = Math.floor(newValue).toLocaleString();
      } else if (id.includes('gdp') || id.includes('value') || id.includes('tons') || id.includes('barrels')) {
        elem.textContent = newValue.toFixed(1).toLocaleString();
      } else if (id.includes('temp') || id.includes('rate') || id.includes('pct')) {
        elem.textContent = newValue.toFixed(1) + (id.includes('temp') ? '°C' : id.includes('rate') ? '%' : '');
      } else if (id.includes('date')) {
        // Update simulation time
        state.simulationTime = new Date(state.simulationTime.getTime() + 3600000 * state.simulationSpeed);
        elem.textContent = state.simulationTime.toISOString().split('T')[0];
      } else {
        elem.textContent = newValue.toFixed(1);
      }
    }
  };
  
  // Update various data points
  updateValue('global-pop', 8123456789);
  updateValue('global-gdp', 105.2);
  updateValue('global-temp', 1.2);
  updateValue('sea-level', 3.3);
  updateValue('active-volcanoes', 43);
  updateValue('earthquakes-24h', 312);
  updateValue('active-storms', 47);
  updateValue('hurricanes', 12);
  updateValue('cyclones', 15);
  
  // Update simulation time display
  const timeElem = document.getElementById('current-time');
  if (timeElem) {
    const simTime = new Date(state.simulationTime.getTime() + 3600000 * state.simulationSpeed);
    timeElem.textContent = simTime.toISOString().replace('T', ' ').substring(0, 19) + ' UTC';
  }
}

function updateSimulationTime() {
  state.simulationTime = new Date(state.simulationTime.getTime() + 3600000 * state.simulationSpeed);
  
  const dateOverlay = document.getElementById('current-date-overlay');
  const simSpeed = document.getElementById('sim-speed-overlay');
  
  if (dateOverlay) {
    dateOverlay.textContent = state.simulationTime.toISOString().split('T')[0];
  }
  
  if (simSpeed) {
    simSpeed.textContent = `SPEED: ${state.simulationSpeed}x`;
  }
}

function initializeGlobe() {
  const canvas = document.getElementById('globe-canvas');
  if (!canvas) return;
  
  const ctx = canvas.getContext('2d');
  const width = canvas.width = canvas.offsetWidth;
  const height = canvas.height = canvas.offsetHeight;
  
  // Simple rotating globe animation
  let rotation = 0;
  
  function drawGlobe() {
    ctx.clearRect(0, 0, width, height);
    
    // Draw globe
    const centerX = width / 2;
    const centerY = height / 2;
    const radius = Math.min(width, height) / 2 - 20;
    
    // Globe background
    ctx.beginPath();
    ctx.arc(centerX, centerY, radius, 0, Math.PI * 2);
    const gradient = ctx.createRadialGradient(centerX - radius/3, centerY - radius/3, 0, centerX, centerY, radius);
    gradient.addColorStop(0, '#1e293b');
    gradient.addColorStop(1, '#0f172a');
    ctx.fillStyle = gradient;
    ctx.fill();
    
    // Globe grid
    ctx.strokeStyle = 'rgba(56, 189, 248, 0.2)';
    ctx.lineWidth = 1;
    
    // Latitude lines
    for (let i = 0; i < 6; i++) {
      const y = centerY - radius/2 + (i * radius/5);
      ctx.beginPath();
      ctx.ellipse(centerX, centerY, radius * Math.cos(Math.asin((y - centerY) / radius)), radius * Math.abs(Math.sin(Math.asin((y - centerY) / radius))), 0, 0, Math.PI * 2);
      ctx.stroke();
    }
    
    // Longitude lines (rotating)
    for (let i = 0; i < 8; i++) {
      const angle = (i * Math.PI / 4) + rotation;
      ctx.beginPath();
      ctx.moveTo(centerX + radius * Math.cos(angle), centerY);
      ctx.quadraticCurveTo(
        centerX + radius * Math.cos(angle) * 0.7,
        centerY + radius * 0.3,
        centerX + radius * Math.cos(angle + Math.PI),
        centerY
      );
      ctx.stroke();
    }
    
    rotation += 0.005;
    requestAnimationFrame(drawGlobe);
  }
  
  drawGlobe();
}

function setupTabSwitching() {
  const tabBtns = document.querySelectorAll('.tab-btn');
  const tabContents = document.querySelectorAll('.tab-content');
  
  tabBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      const tabId = btn.dataset.tab;
      
      // Remove active class from all
      tabBtns.forEach(b => b.classList.remove('active'));
      tabContents.forEach(c => c.classList.remove('active'));
      
      // Add active to clicked
      btn.classList.add('active');
      const targetTab = document.getElementById(`tab-${tabId}`);
      if (targetTab) {
        targetTab.classList.add('active');
      }
    });
  });
}

// Utility: Random number in range
function random(min, max) {
  return Math.random() * (max - min) + min;
}

// Utility: Format number with commas
function formatNumber(num) {
  return num.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}

// Handle window resize for canvas
window.addEventListener('resize', () => {
  const canvas = document.getElementById('globe-canvas');
  if (canvas) {
    canvas.width = canvas.offsetWidth;
    canvas.height = canvas.offsetHeight;
  }
});

// Keyboard shortcuts
document.addEventListener('keydown', (e) => {
  if (e.key === ' ') {
    // Space bar to pause/resume
    state.isRunning = !state.isRunning;
    if (state.isRunning) {
      startSimulation();
    } else {
      clearInterval(state.dataRefreshInterval);
    }
  } else if (e.key === 'ArrowUp') {
    // Increase speed
    state.simulationSpeed = Math.min(10, state.simulationSpeed + 1);
    updateSimulationTime();
  } else if (e.key === 'ArrowDown') {
    // Decrease speed
    state.simulationSpeed = Math.max(1, state.simulationSpeed - 1);
    updateSimulationTime();
  }
});

console.log('🌍 Planet Simulation Dashboard initialized');
console.log('Keyboard shortcuts:');
console.log('  Space - Pause/Resume');
console.log('  Arrow Up - Increase simulation speed');
console.log('  Arrow Down - Decrease simulation speed');